function [ ELt, ELp ] = EL_terms(matrix, K11, K22, K33, deltax, deltay, deltaz, wbcMatrix)


Nt = matrix(:,:,:,1);
Np = matrix(:,:,:,2);


[dNtdx, dNtdy, dNtdz] = gradient(Nt, deltax, deltay, deltaz);
[d2Ntdxdx, d2Ntdxdy, d2Ntdxdz] = gradient(dNtdx,deltax,deltay,deltaz);
[~, d2Ntdydy, d2Ntdydz] = gradient(dNtdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Ntdzdz] = gradient(dNtdz,deltax,deltay,deltaz); % 2 repeats


[dNpdx, dNpdy, dNpdz] = gradient(Np, deltax, deltay, deltaz);
[d2Npdxdx, d2Npdxdy, d2Npdxdz] = gradient(dNpdx,deltax,deltay,deltaz);
[~, d2Npdydy, d2Npdydz] = gradient(dNpdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Npdzdz] = gradient(dNpdz,deltax,deltay,deltaz); % 2 repeats


%% Oseen Frank

ELp = zeros(size(matrix(:,:,:,1)));
ELt = zeros(size(matrix(:,:,:,2)));

a = wbcMatrix(:,:,:,1);
b = wbcMatrix(:,:,:,2);
Ws = wbcMatrix(:,:,:,3);

%{
ELts = (1/4).*K11.*(2.*d2Npdydz.*cos(Np)+(-2).*dNpdx.*dNpdz.*cos(Np)+(-2).* ...
  d2Npdydz.*cos(Nt).^2.*cos(Np)+2.*dNpdx.*dNpdz.*cos(Nt).^2.*cos(Np)+(-4).* ...
  d2Ntdxdx.*cos(Nt).^2.*cos(Np).^2+(-4).*dNtdy.*dNpdx.*cos(Nt).^2.*cos(Np) ...
  .^2+(-4).*dNtdx.*dNpdy.*cos(Nt).^2.*cos(Np).^2+(-4).*d2Ntdzdz.*sin(Nt) ...
  .^2+2.*d2Npdydz.*cos(Np).*sin(Nt).^2+(-2).*dNpdx.*dNpdz.*cos(Np).*sin(Nt) ...
  .^2+(-2).*dNtdz.^2.*sin(2.*Nt)+4.*d2Ntdxdz.*cos(Np).*sin(2.*Nt)+2.* ...
  dNtdy.*dNpdz.*cos(Np).*sin(2.*Nt)+(-2).*d2Npdxdy.*cos(Np).^2.*sin(2.*Nt)+ ...
  2.*dNtdx.^2.*cos(Np).^2.*sin(2.*Nt)+2.*dNpdx.^2.*cos(Np).^2.*sin(2.*Nt)+ ...
  (-2).*d2Npdxdz.*sin(Np)+(-2).*dNpdy.*dNpdz.*sin(Np)+2.*d2Npdxdz.*cos(Nt) ...
  .^2.*sin(Np)+2.*dNpdy.*dNpdz.*cos(Nt).^2.*sin(Np)+(-2).*d2Npdxdz.*sin(Nt) ...
  .^2.*sin(Np)+(-2).*dNpdy.*dNpdz.*sin(Nt).^2.*sin(Np)+4.*d2Ntdydz.*sin( ...
  2.*Nt).*sin(Np)+(-2).*dNtdx.*dNpdz.*sin(2.*Nt).*sin(Np)+(-4).*d2Ntdydy.* ...
  cos(Nt).^2.*sin(Np).^2+4.*dNtdy.*dNpdx.*cos(Nt).^2.*sin(Np).^2+4.*dNtdx.* ...
  dNpdy.*cos(Nt).^2.*sin(Np).^2+2.*d2Npdxdy.*sin(2.*Nt).*sin(Np).^2+2.* ...
  dNtdy.^2.*sin(2.*Nt).*sin(Np).^2+2.*dNpdy.^2.*sin(2.*Nt).*sin(Np).^2+2.* ...
  dNtdz.*(2.*dNtdx.*cos(Nt).^2.*cos(Np)+(-2).*dNtdx.*cos(Np).*sin(Nt).^2+ ...
  dNpdy.*cos(Np).*sin(2.*Nt)+2.*dNtdy.*cos(2.*Nt).*sin(Np)+(-1).*dNpdx.* ...
  sin(2.*Nt).*sin(Np))+(-4).*d2Ntdxdy.*cos(Nt).^2.*sin(2.*Np)+4.*dNtdx.* ...
  dNpdx.*cos(Nt).^2.*sin(2.*Np)+(-4).*dNtdy.*dNpdy.*cos(Nt).^2.*sin(2.*Np)+ ...
  d2Npdxdx.*sin(2.*Nt).*sin(2.*Np)+(-1).*d2Npdydy.*sin(2.*Nt).*sin(2.*Np)+ ...
  2.*dNtdx.*dNtdy.*sin(2.*Nt).*sin(2.*Np)+2.*dNpdx.*dNpdy.*sin(2.*Nt).*sin( ...
  2.*Np))+(1/4).*K22.*((-4).*d2Ntdydy.*cos(Np).^2+4.*dNtdx.*dNpdy.*cos(Np) ...
  .^2+(-4).*d2Npdydz.*cos(Np).*sin(Nt).^2+8.*dNpdz.^2.*cos(Nt).*sin(Nt) ...
  .^3+2.*d2Npdxdy.*cos(Np).^2.*sin(2.*Nt)+(-2).*dNpdx.^2.*cos(Np).^2.* ...
  sin(2.*Nt)+2.*dNpdy.^2.*cos(Np).^2.*sin(2.*Nt)+dNpdx.^2.*cos(Np).^2.* ...
  sin(4.*Nt)+4.*d2Npdxdz.*sin(Nt).^2.*sin(Np)+(-4).*d2Ntdxdx.*sin(Np).^2+( ...
  -4).*dNtdx.*dNpdy.*sin(Np).^2+(-2).*d2Npdxdy.*sin(2.*Nt).*sin(Np).^2+2.* ...
  dNpdx.^2.*sin(2.*Nt).*sin(Np).^2+(-2).*dNpdy.^2.*sin(2.*Nt).*sin(Np).^2+ ...
  dNpdy.^2.*sin(4.*Nt).*sin(Np).^2+(-8).*dNpdz.*cos(2.*Nt).*sin(Nt).^2.*( ...
  dNpdx.*cos(Np)+dNpdy.*sin(Np))+4.*d2Ntdxdy.*sin(2.*Np)+(-4).*dNtdx.* ...
  dNpdx.*sin(2.*Np)+(-1).*d2Npdxdx.*sin(2.*Nt).*sin(2.*Np)+d2Npdydy.*sin( ...
  2.*Nt).*sin(2.*Np)+(-4).*dNpdx.*dNpdy.*sin(2.*Nt).*sin(2.*Np)+dNpdx.* ...
  dNpdy.*sin(4.*Nt).*sin(2.*Np)+4.*dNtdy.*(dNpdx.*cos(2.*Np)+dNpdy.*sin(2.* ...
  Np)))+K33.*((-1/2).*d2Ntdzdz+(-1/2).*d2Ntdzdz.*cos(2.*Nt)+(-1).*dNtdx.* ...
  dNtdz.*cos(2.*Nt).*cos(Np)+(-1).*d2Ntdxdx.*cos(Np).^2.*sin(Nt).^2+(-1).* ...
  dNtdy.*dNpdx.*cos(Np).^2.*sin(Nt).^2+(-1).*dNtdx.*dNpdy.*cos(Np).^2.*sin( ...
  Nt).^2+dNtdz.^2.*sin(2.*Nt)+(-1).*d2Ntdxdz.*cos(Np).*sin(2.*Nt)+(-1/2).* ...
  dNtdy.*dNpdz.*cos(Np).*sin(2.*Nt)+(-1).*dNtdx.^2.*cos(Np).^2.*sin(2.*Nt)+ ...
  (-1).*dNtdy.*dNtdz.*cos(2.*Nt).*sin(Np)+(-1).*d2Ntdydz.*sin(2.*Nt).*sin( ...
  Np)+(1/2).*dNtdx.*dNpdz.*sin(2.*Nt).*sin(Np)+(-1).*d2Ntdydy.*sin(Nt).^2.* ...
  sin(Np).^2+dNtdy.*dNpdx.*sin(Nt).^2.*sin(Np).^2+dNtdx.*dNpdy.*sin(Nt).^2.* ...
  sin(Np).^2+(-1).*dNtdy.^2.*sin(2.*Nt).*sin(Np).^2+(-1/2).*dNtdz.*( ...
  dNpdy.*cos(Np).*sin(2.*Nt)+2.*dNtdy.*cos(2.*Nt).*sin(Np))+(-1/2).*dNtdz.* ...
  (2.*dNtdx.*cos(2.*Nt).*cos(Np)+(-1).*dNpdx.*sin(2.*Nt).*sin(Np))+(-1).* ...
  d2Ntdxdy.*sin(Nt).^2.*sin(2.*Np)+dNtdx.*dNpdx.*sin(Nt).^2.*sin(2.*Np)+( ...
  -1).*dNtdy.*dNpdy.*sin(Nt).^2.*sin(2.*Np)+(-1).*dNtdx.*dNtdy.*sin(2.*Nt) ...
  .*sin(2.*Np)+(1/32).*(32.*sin(Nt).^2.*((-1).*dNtdz.*sin(Nt)+cos(Nt).*( ...
  dNtdx.*cos(Np)+dNtdy.*sin(Np))).*(dNtdz.*cos(Nt)+sin(Nt).*(dNtdx.*cos(Np)+ ...
  dNtdy.*sin(Np)))+32.*cos(Nt).*sin(Nt).*(dNtdz.*cos(Nt)+sin(Nt).*(dNtdx.* ...
  cos(Np)+dNtdy.*sin(Np))).^2+(-4).*(4.*dNtdz.*cos(Nt).^2.*cos(Np)+2.* ...
  dNtdx.*sin(2.*Nt)+(-2).*dNpdz.*sin(2.*Nt).*sin(Np)+(-4).*dNpdy.*sin(Nt) ...
  .^2.*sin(Np).^2+(-2).*dNtdx.*sin(2.*Nt).*sin(Np).^2+(-2).*dNpdx.*sin(Nt) ...
  .^2.*sin(2.*Np)+dNtdy.*sin(2.*Nt).*sin(2.*Np)).*((-2).*dNtdx.*cos(2.*Nt) ...
  +2.*dNtdz.*cos(Np).*sin(2.*Nt)+2.*dNpdz.*cos(2.*Nt).*sin(Np)+2.*dNtdx.* ...
  cos(2.*Nt).*sin(Np).^2+2.*dNpdy.*sin(2.*Nt).*sin(Np).^2+(-1).*dNtdy.* ...
  cos(2.*Nt).*sin(2.*Np)+dNpdx.*sin(2.*Nt).*sin(2.*Np))+2.*(4.*dNpdx.*cos( ...
  Np).^2.*sin(Nt).^2+2.*dNtdy.*sin(2.*Nt)+2.*dNpdz.*cos(Np).*sin(2.*Nt)+( ...
  -2).*dNtdy.*cos(Np).^2.*sin(2.*Nt)+4.*dNtdz.*cos(Nt).^2.*sin(Np)+2.* ...
  dNpdy.*sin(Nt).^2.*sin(2.*Np)+dNtdx.*sin(2.*Nt).*sin(2.*Np)).*(4.*dNtdy.* ...
  cos(2.*Nt)+4.*dNpdz.*cos(2.*Nt).*cos(Np)+(-4).*dNtdy.*cos(2.*Nt).*cos(Np) ...
  .^2+4.*dNpdx.*cos(Np).^2.*sin(2.*Nt)+(-4).*dNtdz.*sin(2.*Nt).*sin(Np)+ ...
  2.*dNtdx.*cos(2.*Nt).*sin(2.*Np)+2.*dNpdy.*sin(2.*Nt).*sin(2.*Np))));


ELps = (1/8).*K22.*((-4).*dNtdx.*dNtdy.*cos(2.*Nt)+(-8).*dNtdx.*dNtdy.*cos(Np) ...
  .^2+8.*dNtdx.*dNtdy.*cos(2.*Nt).*cos(Np).^2+4.*dNtdx.*dNtdy.*cos(2.*Nt).* ...
  cos(2.*Np)+(-8).*d2Ntdydz.*cos(Np).*sin(Nt).^2+8.*dNtdx.*dNpdz.*cos(Np).* ...
  sin(Nt).^2+16.*dNtdx.*dNpdz.*cos(2.*Nt).*cos(Np).*sin(Nt).^2+16.* ...
  d2Npdxdz.*cos(Nt).*cos(Np).*sin(Nt).^3+8.*dNpdy.*dNpdz.*cos(Nt).*cos(Np).* ...
  sin(Nt).^3+(-8).*d2Npdzdz.*sin(Nt).^4+4.*d2Ntdxdy.*cos(Np).^2.*sin(2.* ...
  Nt)+(-2).*d2Npdxdx.*cos(Np).^2.*sin(2.*Nt).^2+(-2).*dNpdx.*dNpdy.*cos(Np) ...
  .^2.*sin(2.*Nt).^2+(-4).*dNtdx.*dNpdx.*cos(Np).^2.*sin(4.*Nt)+8.* ...
  d2Ntdxdz.*sin(Nt).^2.*sin(Np)+8.*dNtdy.*dNpdz.*sin(Nt).^2.*sin(Np)+16.* ...
  dNtdy.*dNpdz.*cos(2.*Nt).*sin(Nt).^2.*sin(Np)+16.*d2Npdydz.*cos(Nt).*sin( ...
  Nt).^3.*sin(Np)+(-8).*dNpdx.*dNpdz.*cos(Nt).*sin(Nt).^3.*sin(Np)+8.* ...
  dNtdx.*dNtdy.*sin(Np).^2+(-4).*d2Ntdxdy.*sin(2.*Nt).*sin(Np).^2+(-2).* ...
  d2Npdydy.*sin(2.*Nt).^2.*sin(Np).^2+2.*dNpdx.*dNpdy.*sin(2.*Nt).^2.*sin( ...
  Np).^2+(-4).*dNtdy.*dNpdy.*sin(4.*Nt).*sin(Np).^2+(-2).*dNtdz.*(16.* ...
  dNpdz.*cos(Nt).*sin(Nt).^3+(-2).*(2.*dNpdx.*cos(2.*Nt).*cos(Np).*sin(Nt) ...
  .^2+(-2).*dNtdy.*cos(Np).*sin(2.*Nt)+dNpdx.*cos(Np).*sin(2.*Nt).^2+2.* ...
  dNpdy.*(1+2.*cos(2.*Nt)).*sin(Nt).^2.*sin(Np)+2.*dNtdx.*sin(2.*Nt).*sin( ...
  Np)))+4.*dNtdx.^2.*sin(2.*Np)+(-4).*dNtdy.^2.*sin(2.*Np)+(-4).* ...
  dNtdx.^2.*cos(2.*Nt).*sin(2.*Np)+4.*dNtdy.^2.*cos(2.*Nt).*sin(2.*Np)+( ...
  -2).*d2Ntdxdx.*sin(2.*Nt).*sin(2.*Np)+2.*d2Ntdydy.*sin(2.*Nt).*sin(2.* ...
  Np)+(-2).*d2Npdxdy.*sin(2.*Nt).^2.*sin(2.*Np)+dNpdx.^2.*sin(2.*Nt).^2.* ...
  sin(2.*Np)+(-1).*dNpdy.^2.*sin(2.*Nt).^2.*sin(2.*Np)+(-2).*dNtdy.* ...
  dNpdx.*sin(4.*Nt).*sin(2.*Np)+(-2).*dNtdx.*dNpdy.*sin(4.*Nt).*sin(2.*Np)) ...
  +(-1/2).*K11.*sin(Nt).*(2.*dNtdx.*dNpdx.*cos(Nt)+2.*d2Ntdxdy.*cos(Nt).* ...
  cos(Np).^2+(-2).*dNtdx.*dNpdx.*cos(Nt).*cos(Np).^2+d2Npdxdx.*sin(Nt)+ ...
  d2Npdydy.*sin(Nt)+(-2).*d2Ntdydz.*cos(Np).*sin(Nt)+(-1).*d2Npdxdx.*cos( ...
  Np).^2.*sin(Nt)+d2Npdydy.*cos(Np).^2.*sin(Nt)+(-2).*dNpdx.*dNpdy.*cos(Np) ...
  .^2.*sin(Nt)+2.*d2Ntdxdz.*sin(Nt).*sin(Np)+(-2).*d2Ntdxdy.*cos(Nt).*sin( ...
  Np).^2+2.*dNtdx.*dNpdx.*cos(Nt).*sin(Np).^2+d2Npdxdx.*sin(Nt).*sin(Np).^2+ ...
  (-1).*d2Npdydy.*sin(Nt).*sin(Np).^2+2.*dNpdx.*dNpdy.*sin(Nt).*sin(Np).^2+ ...
  (-2).*dNtdz.*cos(Nt).*(dNtdy.*cos(Np)+(-1).*dNtdx.*sin(Np))+(-1).* ...
  d2Ntdxdx.*cos(Nt).*sin(2.*Np)+d2Ntdydy.*cos(Nt).*sin(2.*Np)+(-2).*dNtdx.* ...
  dNpdy.*cos(Nt).*sin(2.*Np)+(-2).*d2Npdxdy.*sin(Nt).*sin(2.*Np)+dNtdx.^2.* ...
  sin(Nt).*sin(2.*Np)+(-1).*dNtdy.^2.*sin(Nt).*sin(2.*Np)+dNpdx.^2.*sin(Nt) ...
  .*sin(2.*Np)+(-1).*dNpdy.^2.*sin(Nt).*sin(2.*Np)+dNtdy.*(4.*dNpdy.*cos( ...
  Nt).*cos(Np).^2+(-2).*dNtdx.*cos(2.*Np).*sin(Nt)+(-2).*dNpdx.*cos(Nt).* ...
  sin(2.*Np)))+K33.*((-1/2).*d2Npdzdz.*sin(Nt).^2+(-1/2).*d2Npdzdz.*cos( ...
  2.*Nt).*sin(Nt).^2+(-2).*dNtdz.*dNpdx.*cos(Nt).^2.*cos(Np).*sin(Nt).^2+( ...
  -2).*d2Npdxdz.*cos(Nt).*cos(Np).*sin(Nt).^3+(-1).*dNpdy.*dNpdz.*cos(Nt).* ...
  cos(Np).*sin(Nt).^3+(-4).*dNtdx.*dNpdx.*cos(Nt).*cos(Np).^2.*sin(Nt).^3+( ...
  -1).*d2Npdxdx.*cos(Np).^2.*sin(Nt).^4+(-2).*dNpdx.*dNpdy.*cos(Np).^2.* ...
  sin(Nt).^4+(-1/2).*dNtdz.*dNpdz.*sin(2.*Nt)+(-1/4).*dNtdz.*dNpdz.*sin( ...
  4.*Nt)+(-2).*d2Npdydz.*cos(Nt).*sin(Nt).^3.*sin(Np)+dNpdx.*dNpdz.*cos(Nt) ...
  .*sin(Nt).^3.*sin(Np)+(-1/2).*dNtdz.*dNpdy.*sin(2.*Nt).^2.*sin(Np)+(-1) ...
  .*d2Npdydy.*sin(Nt).^4.*sin(Np).^2+2.*dNpdx.*dNpdy.*sin(Nt).^4.*sin(Np) ...
  .^2+(-1).*dNtdy.*dNpdy.*sin(2.*Nt).*sin(Np).^2+(1/2).*dNtdy.*dNpdy.*sin( ...
  4.*Nt).*sin(Np).^2+(-1).*dNpdz.*sin(Nt).^2.*(dNpdy.*cos(Nt).*cos(Np).* ...
  sin(Nt)+dNtdy.*(1+2.*cos(2.*Nt)).*sin(Np))+(1/2).*dNpdz.*sin(Nt).^2.*(( ...
  -2).*dNtdx.*(1+2.*cos(2.*Nt)).*cos(Np)+dNpdx.*sin(2.*Nt).*sin(Np))+ ...
  dNtdz.*sin(Nt).^2.*(dNpdz.*sin(2.*Nt)+(-1).*cos(2.*Nt).*(dNpdx.*cos(Np)+ ...
  dNpdy.*sin(Np)))+(-2).*dNtdx.*dNpdy.*cos(Nt).*sin(Nt).^3.*sin(2.*Np)+(-1) ...
  .*d2Npdxdy.*sin(Nt).^4.*sin(2.*Np)+dNpdx.^2.*sin(Nt).^4.*sin(2.*Np)+(-1) ...
  .*dNpdy.^2.*sin(Nt).^4.*sin(2.*Np)+(-1/2).*dNtdy.*dNpdx.*sin(2.*Nt).* ...
  sin(2.*Np)+(1/4).*dNtdy.*dNpdx.*sin(4.*Nt).*sin(2.*Np)+(1/32).*(32.* ...
  sin(Nt).^3.*(dNtdy.*cos(Np)+(-1).*dNtdx.*sin(Np)).*(dNtdz.*cos(Nt)+sin(Nt) ...
  .*(dNtdx.*cos(Np)+dNtdy.*sin(Np)))+4.*(4.*dNpdx.*cos(Np).^2.*sin(Nt).^2+ ...
  2.*dNtdy.*sin(2.*Nt)+2.*dNpdz.*cos(Np).*sin(2.*Nt)+(-2).*dNtdy.*cos(Np) ...
  .^2.*sin(2.*Nt)+4.*dNtdz.*cos(Nt).^2.*sin(Np)+2.*dNpdy.*sin(Nt).^2.*sin( ...
  2.*Np)+dNtdx.*sin(2.*Nt).*sin(2.*Np)).*(2.*dNtdz.*cos(Nt).^2.*cos(Np)+2.* ...
  dNpdy.*cos(2.*Np).*sin(Nt).^2+dNtdx.*cos(2.*Np).*sin(2.*Nt)+(-1).*dNpdz.* ...
  sin(2.*Nt).*sin(Np)+(-2).*dNpdx.*sin(Nt).^2.*sin(2.*Np)+dNtdy.*sin(2.*Nt) ...
  .*sin(2.*Np))+(-4).*(2.*dNpdx.*cos(2.*Np).*sin(Nt).^2+dNpdz.*cos(Np).* ...
  sin(2.*Nt)+(-1).*dNtdy.*cos(2.*Np).*sin(2.*Nt)+2.*dNtdz.*cos(Nt).^2.* ...
  sin(Np)+2.*dNpdy.*sin(Nt).^2.*sin(2.*Np)+dNtdx.*sin(2.*Nt).*sin(2.*Np)).* ...
  (4.*dNtdz.*cos(Nt).^2.*cos(Np)+2.*dNtdx.*sin(2.*Nt)+(-2).*dNpdz.*sin(2.* ...
  Nt).*sin(Np)+(-4).*dNpdy.*sin(Nt).^2.*sin(Np).^2+(-2).*dNtdx.*sin(2.*Nt) ...
  .*sin(Np).^2+(-2).*dNpdx.*sin(Nt).^2.*sin(2.*Np)+dNtdy.*sin(2.*Nt).*sin( ...
  2.*Np))));

%}

%Since Ws should be zero outside 
ELt = K11.*((-1).*dNtdz.*cos(Nt)+cos(Np).*(dNpdy.*cos(Nt)+(-1).*dNtdx.*sin(Nt)) ...
  +((-1).*dNpdx.*cos(Nt)+(-1).*dNtdy.*sin(Nt)).*sin(Np)).*((-1).*dNtdz.* ...
  sin(Nt)+cos(Np).*(dNtdx.*cos(Nt)+dNpdy.*sin(Nt))+(dNtdy.*cos(Nt)+(-1).* ...
  dNpdx.*sin(Nt)).*sin(Np))+(1/2).*((-1).*d2Ntdzdz.*(K11+K33+((-1).*K11+ ...
  K33).*cos(2.*Nt))+d2Npdydz.*K11.*cos(Np)+(-1).*dNpdx.*dNpdz.*K11.*cos( ...
  Np)+(-1).*d2Npdydz.*K11.*cos(Nt).^2.*cos(Np)+dNpdx.*dNpdz.*K11.*cos(Nt) ...
  .^2.*cos(Np)+2.*dNtdx.*dNtdz.*K11.*cos(2.*Nt).*cos(Np)+(-2).*dNtdx.* ...
  dNtdz.*K33.*cos(2.*Nt).*cos(Np)+d2Npdydz.*K11.*cos(Np).*sin(Nt).^2+(-1) ...
  .*dNpdx.*dNpdz.*K11.*cos(Np).*sin(Nt).^2+(-2).*dNtdz.^2.*(K11+(-1).* ...
  K33).*sin(2.*Nt)+d2Ntdxdz.*K11.*cos(Np).*sin(2.*Nt)+2.*dNtdz.*dNpdy.* ...
  K11.*cos(Np).*sin(2.*Nt)+dNtdy.*dNpdz.*(K11+(-1).*K33).*cos(Np).*sin( ...
  2.*Nt)+(-1).*d2Ntdxdz.*K33.*cos(Np).*sin(2.*Nt)+(-1).*d2Npdxdz.*K11.* ...
  sin(Np)+(-1).*dNpdy.*dNpdz.*K11.*sin(Np)+d2Npdxdz.*K11.*cos(Nt).^2.*sin( ...
  Np)+dNpdy.*dNpdz.*K11.*cos(Nt).^2.*sin(Np)+2.*dNtdy.*dNtdz.*(K11+(-1).* ...
  K33).*cos(2.*Nt).*sin(Np)+(-1).*d2Npdxdz.*K11.*sin(Nt).^2.*sin(Np)+(-1) ...
  .*dNpdy.*dNpdz.*K11.*sin(Nt).^2.*sin(Np)+(-2).*dNtdz.*dNpdx.*K11.*sin( ...
  2.*Nt).*sin(Np)+(-1).*dNtdx.*dNpdz.*K11.*sin(2.*Nt).*sin(Np)+d2Ntdydz.*( ...
  K11+(-1).*K33).*sin(2.*Nt).*sin(Np)+dNtdx.*dNpdz.*K33.*sin(2.*Nt).*sin( ...
  Np))+(1/4).*K22.*(2.*dNpdx.*cos(2.*Nt).*cos(Np)+(-4).*dNpdz.*cos(Nt).* ...
  sin(Nt)+2.*dNpdy.*cos(2.*Nt).*sin(Np)).*((-2).*dNpdz.*sin(Nt).^2+cos(Np) ...
  .*((-2).*dNtdy+dNpdx.*sin(2.*Nt))+(2.*dNtdx+dNpdy.*sin(2.*Nt)).*sin(Np))+ ...
  (1/4).*(4.*dNtdy.*dNpdx.*K22.*cos(Np).^2+(-4).*d2Ntdxdx.*K11.*cos(Nt) ...
  .^2.*cos(Np).^2+(-4).*dNtdy.*dNpdx.*K11.*cos(Nt).^2.*cos(Np).^2+(-4).* ...
  dNtdx.*dNpdy.*K11.*cos(Nt).^2.*cos(Np).^2+4.*dNtdx.*dNpdy.*K11.*cos(Np) ...
  .^2.*sin(Nt).^2+(-4).*d2Ntdxdx.*K33.*cos(Np).^2.*sin(Nt).^2+(-4).* ...
  dNtdy.*dNpdx.*K33.*cos(Np).^2.*sin(Nt).^2+2.*d2Ntdxdz.*K11.*cos(Np).* ...
  sin(2.*Nt)+(-2).*d2Ntdxdz.*K33.*cos(Np).*sin(2.*Nt)+(-2).*d2Npdxdy.* ...
  K11.*cos(Np).^2.*sin(2.*Nt)+4.*dNtdx.^2.*K11.*cos(Np).^2.*sin(2.*Nt)+ ...
  2.*dNpdx.^2.*K11.*cos(Np).^2.*sin(2.*Nt)+(-2).*dNpdx.^2.*K22.*cos(Np) ...
  .^2.*sin(2.*Nt)+(-4).*dNtdx.^2.*K33.*cos(Np).^2.*sin(2.*Nt)+4.* ...
  d2Npdxdz.*K22.*sin(Nt).^2.*sin(Np)+(-4).*d2Ntdxdx.*K22.*sin(Np).^2+(-4) ...
  .*dNtdy.*dNpdx.*K22.*sin(Np).^2+4.*dNtdy.*dNpdx.*K11.*cos(Nt).^2.*sin(Np) ...
  .^2+(-4).*dNtdx.*dNpdy.*K22.*cos(2.*Nt).*sin(Np).^2+4.*dNtdy.*dNpdx.* ...
  K33.*sin(Nt).^2.*sin(Np).^2+(-2).*dNpdx.^2.*K11.*sin(2.*Nt).*sin(Np) ...
  .^2+(-2).*d2Npdxdy.*K22.*sin(2.*Nt).*sin(Np).^2+2.*dNpdx.^2.*K22.*sin( ...
  2.*Nt).*sin(Np).^2+4.*dNpdz.*K22.*(dNpdx.*cos(Np).*sin(Nt).^2+dNtdx.*sin( ...
  2.*Nt).*sin(Np))+2.*dNtdz.*(K11+(-1).*K33).*(2.*dNtdx.*cos(2.*Nt).*cos( ...
  Np)+(-1).*dNpdx.*sin(2.*Nt).*sin(Np))+2.*d2Ntdxdy.*K22.*sin(2.*Np)+(-4) ...
  .*dNtdx.*dNpdx.*K22.*sin(2.*Np)+(-2).*d2Ntdxdy.*K11.*cos(Nt).^2.*sin( ...
  2.*Np)+6.*dNtdx.*dNpdx.*K11.*cos(Nt).^2.*sin(2.*Np)+(-2).*dNtdx.*dNpdx.* ...
  K22.*cos(2.*Nt).*sin(2.*Np)+(-2).*dNtdx.*dNpdx.*K11.*sin(Nt).^2.*sin( ...
  2.*Np)+(-2).*d2Ntdxdy.*K33.*sin(Nt).^2.*sin(2.*Np)+4.*dNtdx.*dNpdx.* ...
  K33.*sin(Nt).^2.*sin(2.*Np)+d2Npdxdx.*K11.*sin(2.*Nt).*sin(2.*Np)+2.* ...
  dNtdx.*dNtdy.*K11.*sin(2.*Nt).*sin(2.*Np)+2.*dNpdx.*dNpdy.*K11.*sin(2.* ...
  Nt).*sin(2.*Np)+(-1).*d2Npdxdx.*K22.*sin(2.*Nt).*sin(2.*Np)+(-2).* ...
  dNpdx.*dNpdy.*K22.*sin(2.*Nt).*sin(2.*Np)+(-2).*dNtdx.*dNtdy.*K33.*sin( ...
  2.*Nt).*sin(2.*Np))+(1/4).*((-4).*d2Ntdydy.*K22.*cos(Np).^2+4.*dNtdx.* ...
  dNpdy.*K22.*cos(Np).^2+(-4).*dNtdx.*dNpdy.*K11.*cos(Nt).^2.*cos(Np).^2+ ...
  4.*dNtdy.*dNpdx.*K22.*cos(2.*Nt).*cos(Np).^2+(-4).*d2Npdydz.*K22.*cos( ...
  Np).*sin(Nt).^2+(-4).*dNtdx.*dNpdy.*K33.*cos(Np).^2.*sin(Nt).^2+(-2).* ...
  dNpdy.^2.*K11.*cos(Np).^2.*sin(2.*Nt)+2.*d2Npdxdy.*K22.*cos(Np).^2.* ...
  sin(2.*Nt)+2.*dNpdy.^2.*K22.*cos(Np).^2.*sin(2.*Nt)+2.*d2Ntdydz.*K11.* ...
  sin(2.*Nt).*sin(Np)+(-2).*d2Ntdydz.*K33.*sin(2.*Nt).*sin(Np)+(-4).* ...
  dNtdx.*dNpdy.*K22.*sin(Np).^2+(-4).*d2Ntdydy.*K11.*cos(Nt).^2.*sin(Np) ...
  .^2+4.*dNtdy.*dNpdx.*K11.*cos(Nt).^2.*sin(Np).^2+4.*dNtdx.*dNpdy.*K11.* ...
  cos(Nt).^2.*sin(Np).^2+(-4).*dNtdy.*dNpdx.*K11.*sin(Nt).^2.*sin(Np).^2+( ...
  -4).*d2Ntdydy.*K33.*sin(Nt).^2.*sin(Np).^2+4.*dNtdx.*dNpdy.*K33.*sin(Nt) ...
  .^2.*sin(Np).^2+2.*d2Npdxdy.*K11.*sin(2.*Nt).*sin(Np).^2+4.*dNtdy.^2.* ...
  K11.*sin(2.*Nt).*sin(Np).^2+2.*dNpdy.^2.*K11.*sin(2.*Nt).*sin(Np).^2+( ...
  -2).*dNpdy.^2.*K22.*sin(2.*Nt).*sin(Np).^2+(-4).*dNtdy.^2.*K33.*sin( ...
  2.*Nt).*sin(Np).^2+2.*dNtdz.*(K11+(-1).*K33).*(dNpdy.*cos(Np).*sin(2.* ...
  Nt)+2.*dNtdy.*cos(2.*Nt).*sin(Np))+(-4).*dNpdz.*K22.*(dNtdy.*cos(Np).* ...
  sin(2.*Nt)+(-1).*dNpdy.*sin(Nt).^2.*sin(Np))+2.*d2Ntdxdy.*K22.*sin(2.* ...
  Np)+2.*dNtdy.*dNpdy.*K22.*sin(2.*Np)+(-2).*d2Ntdxdy.*K11.*cos(Nt).^2.* ...
  sin(2.*Np)+(-6).*dNtdy.*dNpdy.*K11.*cos(Nt).^2.*sin(2.*Np)+4.*dNtdy.* ...
  dNpdy.*K22.*cos(Nt).^2.*sin(2.*Np)+2.*dNtdy.*dNpdy.*K11.*sin(Nt).^2.* ...
  sin(2.*Np)+(-2).*d2Ntdxdy.*K33.*sin(Nt).^2.*sin(2.*Np)+(-4).*dNtdy.* ...
  dNpdy.*K33.*sin(Nt).^2.*sin(2.*Np)+(-1).*d2Npdydy.*K11.*sin(2.*Nt).* ...
  sin(2.*Np)+2.*dNtdx.*dNtdy.*K11.*sin(2.*Nt).*sin(2.*Np)+2.*dNpdx.*dNpdy.* ...
  K11.*sin(2.*Nt).*sin(2.*Np)+d2Npdydy.*K22.*sin(2.*Nt).*sin(2.*Np)+(-2) ...
  .*dNpdx.*dNpdy.*K22.*sin(2.*Nt).*sin(2.*Np)+(-2).*dNtdx.*dNtdy.*K33.* ...
  sin(2.*Nt).*sin(2.*Np))+(1/32).*K33.*(32.*sin(Nt).^2.*((-1).*dNtdz.* ...
  sin(Nt)+cos(Nt).*(dNtdx.*cos(Np)+dNtdy.*sin(Np))).*(dNtdz.*cos(Nt)+sin(Nt) ...
  .*(dNtdx.*cos(Np)+dNtdy.*sin(Np)))+32.*cos(Nt).*sin(Nt).*(dNtdz.*cos(Nt)+ ...
  sin(Nt).*(dNtdx.*cos(Np)+dNtdy.*sin(Np))).^2+2.*(4.*dNtdy.*cos(2.*Nt)+4.* ...
  dNpdz.*cos(2.*Nt).*cos(Np)+(-4).*dNtdy.*cos(2.*Nt).*cos(Np).^2+8.*dNpdx.* ...
  cos(Nt).*cos(Np).^2.*sin(Nt)+(-8).*dNtdz.*cos(Nt).*sin(Nt).*sin(Np)+2.* ...
  dNtdx.*cos(2.*Nt).*sin(2.*Np)+4.*dNpdy.*cos(Nt).*sin(Nt).*sin(2.*Np)).*( ...
  4.*dNpdx.*cos(Np).^2.*sin(Nt).^2+2.*dNtdy.*sin(2.*Nt)+2.*dNpdz.*cos(Np).* ...
  sin(2.*Nt)+(-2).*dNtdy.*cos(Np).^2.*sin(2.*Nt)+4.*dNtdz.*cos(Nt).^2.* ...
  sin(Np)+2.*dNpdy.*sin(Nt).^2.*sin(2.*Np)+dNtdx.*sin(2.*Nt).*sin(2.*Np))+ ...
  2.*(4.*dNtdx.*cos(2.*Nt)+(-8).*dNtdz.*cos(Nt).*cos(Np).*sin(Nt)+(-4).* ...
  dNpdz.*cos(2.*Nt).*sin(Np)+(-4).*dNtdx.*cos(2.*Nt).*sin(Np).^2+(-8).* ...
  dNpdy.*cos(Nt).*sin(Nt).*sin(Np).^2+2.*dNtdy.*cos(2.*Nt).*sin(2.*Np)+(-4) ...
  .*dNpdx.*cos(Nt).*sin(Nt).*sin(2.*Np)).*(4.*dNtdz.*cos(Nt).^2.*cos(Np)+ ...
  2.*dNtdx.*sin(2.*Nt)+(-2).*dNpdz.*sin(2.*Nt).*sin(Np)+(-4).*dNpdy.*sin( ...
  Nt).^2.*sin(Np).^2+(-2).*dNtdx.*sin(2.*Nt).*sin(Np).^2+(-2).*dNpdx.*sin( ...
  Nt).^2.*sin(2.*Np)+dNtdy.*sin(2.*Nt).*sin(2.*Np)))+(-2).*Ws.*((-1).* ...
  cos(a).*sin(Nt)+cos(Nt).*cos(Np).*cos(b).*sin(a) ...
  +cos(Nt).*sin(Np).*sin(a).*sin(b)).*(cos(Nt).*cos(a)+cos(Np).*cos(b).*sin(Nt).*sin(a)+sin(Nt).*sin(Np) ...
  .*sin(a).*sin(b)); 


ELp = (-1).*dNtdz.*K11.*sin(Nt).*((-2).*dNtdy.*cos(Nt).*cos(Np)+dNpdy.*sin(Nt) ...
  .*sin(Np))+K11.*((-1).*dNtdz.*sin(Nt)+cos(Np).*(dNtdx.*cos(Nt)+dNpdy.* ...
  sin(Nt))+(dNtdy.*cos(Nt)+(-1).*dNpdx.*sin(Nt)).*sin(Np)).*(cos(Np).*( ...
  dNtdy.*cos(Nt)+(-1).*dNpdx.*sin(Nt))+(-1).*(dNtdx.*cos(Nt)+dNpdy.*sin(Nt)) ...
  .*sin(Np))+(-1).*dNtdz.*cos(Nt).*sin(Nt).*(dNpdz.*(K22+K33+((-1).*K22+ ...
  K33).*cos(2.*Nt))+2.*dNtdy.*K22.*cos(Np)+(-1).*dNpdx.*K22.*cos(Np).* ...
  sin(2.*Nt)+dNpdx.*K33.*cos(Np).*sin(2.*Nt)+(-2).*dNtdx.*K22.*sin(Np)+( ...
  -1).*dNpdy.*K22.*sin(2.*Nt).*sin(Np)+dNpdy.*K33.*sin(2.*Nt).*sin(Np))+( ...
  1/4).*K22.*(cos(Np).*(2.*dNtdx+dNpdy.*sin(2.*Nt))+(-1).*((-2).*dNtdy+ ...
  dNpdx.*sin(2.*Nt)).*sin(Np)).*((-2).*dNpdz.*sin(Nt).^2+cos(Np).*((-2).* ...
  dNtdy+dNpdx.*sin(2.*Nt))+(2.*dNtdx+dNpdy.*sin(2.*Nt)).*sin(Np))+(-1/2).* ...
  sin(Nt).^2.*(d2Npdzdz.*(K22+K33+((-1).*K22+K33).*cos(2.*Nt))+2.* ...
  d2Ntdydz.*K22.*cos(Np)+(-2).*dNtdx.*dNpdz.*K22.*cos(Np)+(-1).*d2Npdxdz.* ...
  K22.*cos(Np).*sin(2.*Nt)+(-1).*dNpdy.*dNpdz.*K22.*cos(Np).*sin(2.*Nt)+ ...
  d2Npdxdz.*K33.*cos(Np).*sin(2.*Nt)+dNpdy.*dNpdz.*K33.*cos(Np).*sin(2.*Nt) ...
  +(-2).*d2Ntdxdz.*K22.*sin(Np)+(-2).*dNtdy.*dNpdz.*K22.*sin(Np)+(-1).* ...
  d2Npdydz.*K22.*sin(2.*Nt).*sin(Np)+dNpdx.*dNpdz.*K22.*sin(2.*Nt).*sin(Np) ...
  +d2Npdydz.*K33.*sin(2.*Nt).*sin(Np)+(-1).*dNpdx.*dNpdz.*K33.*sin(2.*Nt) ...
  .*sin(Np)+2.*dNtdz.*(K22+(-1).*K33).*(dNpdz.*sin(2.*Nt)+(-1).*cos(2.* ...
  Nt).*(dNpdx.*cos(Np)+dNpdy.*sin(Np))))+(1/4).*(4.*dNtdx.*dNtdy.*K22.*cos( ...
  2.*Nt).*cos(Np).^2+4.*dNpdx.*dNpdy.*K11.*cos(Np).^2.*sin(Nt).^2+4.* ...
  d2Npdxdz.*K22.*cos(Nt).*cos(Np).*sin(Nt).^3+(-4).*d2Npdxdz.*K33.*cos(Nt) ...
  .*cos(Np).*sin(Nt).^3+(-16).*dNtdx.*dNpdx.*K33.*cos(Nt).*cos(Np).^2.* ...
  sin(Nt).^3+(-4).*d2Npdxdx.*K33.*cos(Np).^2.*sin(Nt).^4+(-4).*dNpdx.* ...
  dNpdy.*K33.*cos(Np).^2.*sin(Nt).^4+2.*dNtdx.*dNpdx.*K11.*cos(Np).^2.* ...
  sin(2.*Nt)+2.*d2Ntdxdy.*K22.*cos(Np).^2.*sin(2.*Nt)+(-2).*dNtdx.*dNpdx.* ...
  K22.*cos(Np).^2.*sin(2.*Nt)+(-1).*d2Npdxdx.*K22.*cos(Np).^2.*sin(2.*Nt) ...
  .^2+(-1).*dNpdx.*dNpdy.*K22.*cos(Np).^2.*sin(2.*Nt).^2+(-2).*dNtdx.* ...
  dNpdx.*K22.*cos(Np).^2.*sin(4.*Nt)+(-4).*d2Ntdxdz.*K11.*sin(Nt).^2.* ...
  sin(Np)+4.*dNtdx.*dNtdy.*K11.*cos(Nt).^2.*sin(Np).^2+(-4).*d2Npdxdx.* ...
  K11.*sin(Nt).^2.*sin(Np).^2+(-4).*dNtdx.*dNtdy.*K11.*sin(Nt).^2.*sin(Np) ...
  .^2+(-4).*dNpdx.*dNpdy.*K11.*sin(Nt).^2.*sin(Np).^2+4.*dNpdx.*dNpdy.* ...
  K33.*sin(Nt).^4.*sin(Np).^2+2.*d2Ntdxdy.*K11.*sin(2.*Nt).*sin(Np).^2+( ...
  -6).*dNtdx.*dNpdx.*K11.*sin(2.*Nt).*sin(Np).^2+2.*dNtdx.*dNpdx.*K22.* ...
  sin(2.*Nt).*sin(Np).^2+dNpdx.*dNpdy.*K22.*sin(2.*Nt).^2.*sin(Np).^2+(-4) ...
  .*dNtdz.*K11.*(dNpdx.*cos(Np).*sin(Nt).^2+dNtdx.*sin(2.*Nt).*sin(Np))+( ...
  -2).*dNpdz.*(K22+(-1).*K33).*sin(Nt).^2.*((-2).*dNtdx.*(1+2.*cos(2.* ...
  Nt)).*cos(Np)+dNpdx.*sin(2.*Nt).*sin(Np))+2.*dNtdx.^2.*K11.*cos(Nt).^2.* ...
  sin(2.*Np)+(-2).*dNtdx.^2.*K22.*cos(2.*Nt).*sin(2.*Np)+2.*d2Npdxdy.* ...
  K11.*sin(Nt).^2.*sin(2.*Np)+(-2).*dNtdx.^2.*K11.*sin(Nt).^2.*sin(2.*Np) ...
  +(-4).*dNpdx.^2.*K11.*sin(Nt).^2.*sin(2.*Np)+(-8).*dNtdx.*dNpdy.*K33.* ...
  cos(Nt).*sin(Nt).^3.*sin(2.*Np)+(-2).*d2Npdxdy.*K33.*sin(Nt).^4.*sin( ...
  2.*Np)+4.*dNpdx.^2.*K33.*sin(Nt).^4.*sin(2.*Np)+d2Ntdxdx.*K11.*sin(2.* ...
  Nt).*sin(2.*Np)+2.*dNtdy.*dNpdx.*K11.*sin(2.*Nt).*sin(2.*Np)+2.*dNtdx.* ...
  dNpdy.*K11.*sin(2.*Nt).*sin(2.*Np)+(-1).*d2Ntdxdx.*K22.*sin(2.*Nt).* ...
  sin(2.*Np)+(-2).*dNtdy.*dNpdx.*K22.*sin(2.*Nt).*sin(2.*Np)+(-1/2).* ...
  d2Npdxdy.*K22.*sin(2.*Nt).^2.*sin(2.*Np)+dNpdx.^2.*K22.*sin(2.*Nt).^2.* ...
  sin(2.*Np)+(-1).*dNtdx.*dNpdy.*K22.*sin(4.*Nt).*sin(2.*Np))+(1/32).* ...
  K33.*(32.*sin(Nt).^3.*(dNtdy.*cos(Np)+(-1).*dNtdx.*sin(Np)).*(dNtdz.* ...
  cos(Nt)+sin(Nt).*(dNtdx.*cos(Np)+dNtdy.*sin(Np)))+2.*(4.*dNtdz.*cos(Nt) ...
  .^2.*cos(Np)+4.*dNpdy.*cos(2.*Np).*sin(Nt).^2+2.*dNtdx.*cos(2.*Np).*sin( ...
  2.*Nt)+(-8).*dNpdx.*cos(Np).*sin(Nt).^2.*sin(Np)+(-2).*dNpdz.*sin(2.*Nt) ...
  .*sin(Np)+4.*dNtdy.*cos(Np).*sin(2.*Nt).*sin(Np)).*(4.*dNpdx.*cos(Np) ...
  .^2.*sin(Nt).^2+2.*dNtdy.*sin(2.*Nt)+2.*dNpdz.*cos(Np).*sin(2.*Nt)+(-2) ...
  .*dNtdy.*cos(Np).^2.*sin(2.*Nt)+4.*dNtdz.*cos(Nt).^2.*sin(Np)+2.*dNpdy.* ...
  sin(Nt).^2.*sin(2.*Np)+dNtdx.*sin(2.*Nt).*sin(2.*Np))+2.*((-4).*dNpdx.* ...
  cos(2.*Np).*sin(Nt).^2+(-2).*dNpdz.*cos(Np).*sin(2.*Nt)+2.*dNtdy.*cos( ...
  2.*Np).*sin(2.*Nt)+(-4).*dNtdz.*cos(Nt).^2.*sin(Np)+(-8).*dNpdy.*cos(Np) ...
  .*sin(Nt).^2.*sin(Np)+(-4).*dNtdx.*cos(Np).*sin(2.*Nt).*sin(Np)).*(4.* ...
  dNtdz.*cos(Nt).^2.*cos(Np)+2.*dNtdx.*sin(2.*Nt)+(-2).*dNpdz.*sin(2.*Nt).* ...
  sin(Np)+(-4).*dNpdy.*sin(Nt).^2.*sin(Np).^2+(-2).*dNtdx.*sin(2.*Nt).* ...
  sin(Np).^2+(-2).*dNpdx.*sin(Nt).^2.*sin(2.*Np)+dNtdy.*sin(2.*Nt).*sin( ...
  2.*Np)))+(1/8).*(8.*d2Ntdydz.*K11.*cos(Np).*sin(Nt).^2+(-8).*d2Npdydy.* ...
  K11.*cos(Np).^2.*sin(Nt).^2+8.*dNpdx.*dNpdy.*K11.*cos(Np).^2.*sin(Nt) ...
  .^2+(-8).*dNpdx.*dNpdy.*K33.*cos(Np).^2.*sin(Nt).^4+(-4).*d2Ntdxdy.* ...
  K11.*cos(Np).^2.*sin(2.*Nt)+(-2).*dNpdx.*dNpdy.*K22.*cos(Np).^2.*sin( ...
  2.*Nt).^2+8.*d2Npdydz.*K22.*cos(Nt).*sin(Nt).^3.*sin(Np)+(-8).* ...
  d2Npdydz.*K33.*cos(Nt).*sin(Nt).^3.*sin(Np)+(-8).*dNpdx.*dNpdy.*K11.* ...
  sin(Nt).^2.*sin(Np).^2+(-8).*d2Npdydy.*K33.*sin(Nt).^4.*sin(Np).^2+8.* ...
  dNpdx.*dNpdy.*K33.*sin(Nt).^4.*sin(Np).^2+(-4).*d2Ntdxdy.*K22.*sin(2.* ...
  Nt).*sin(Np).^2+(-2).*d2Npdydy.*K22.*sin(2.*Nt).^2.*sin(Np).^2+2.* ...
  dNpdx.*dNpdy.*K22.*sin(2.*Nt).^2.*sin(Np).^2+8.*dNpdz.*(K22+(-1).*K33) ...
  .*sin(Nt).^2.*(dNpdy.*cos(Nt).*cos(Np).*sin(Nt)+dNtdy.*(1+2.*cos(2.*Nt)) ...
  .*sin(Np))+(-4).*dNtdy.^2.*(K11+(-1).*K22).*cos(2.*Nt).*sin(2.*Np)+4.* ...
  d2Npdxdy.*K11.*sin(Nt).^2.*sin(2.*Np)+8.*dNpdy.^2.*K11.*sin(Nt).^2.* ...
  sin(2.*Np)+(-4).*d2Npdxdy.*K33.*sin(Nt).^4.*sin(2.*Np)+(-8).*dNpdy.^2.* ...
  K33.*sin(Nt).^4.*sin(2.*Np)+(-2).*d2Ntdydy.*K11.*sin(2.*Nt).*sin(2.*Np) ...
  +4.*dNtdx.*dNpdy.*K11.*sin(2.*Nt).*sin(2.*Np)+2.*d2Ntdydy.*K22.*sin(2.* ...
  Nt).*sin(2.*Np)+(-4).*dNtdx.*dNpdy.*K22.*sin(2.*Nt).*sin(2.*Np)+(-1).* ...
  d2Npdxdy.*K22.*sin(2.*Nt).^2.*sin(2.*Np)+(-2).*dNpdy.^2.*K22.*sin(2.* ...
  Nt).^2.*sin(2.*Np)+(-2).*dNtdy.*(2.*dNtdx.*cos(2.*Nt).*(K11+K22+(K11+( ...
  -1).*K22).*cos(2.*Np))+2.*dNpdy.*sin(2.*Nt).*((3.*K11+(-1).*K22).* ...
  cos(Np).^2+((-1).*K11+K22+2.*K33+2.*(K22+(-1).*K33).*cos(2.*Nt)).* ...
  sin(Np).^2)+(-2).*dNpdx.*(K11+(-1).*K33+((-1).*K22+K33).*cos(2.*Nt)) ...
  .*sin(2.*Nt).*sin(2.*Np)))+(-2).*Ws.*((-1).*cos(b).*sin(Nt).* ...
  sin(Np).*sin(a)+cos(Np).*sin(Nt).*sin(a).*sin(b) ...
  ).*(cos(Nt).*cos(a)+cos(Np).*cos(b).*sin(Nt).*sin(a)+sin(Nt).*sin(Np).*sin(a).*sin(b));

%{
screen = (~(Ws==0));
ELp(screen) = ELpw(screen);
ELp(~screen) = ELps(~screen);

ELt(screen) = ELtw(screen);
ELt(~screen) = ELts(~screen);
%}

return
end