function [ ELx, ELy, ELz ] = EL_terms_spherical(matrix, K11, K22, K33, deltax, deltay, deltaz)
%%currently running the
%         if nargin < 7
%             deltax = 1;
%             deltay = 1;
%             deltaz = 1;
%         else if nargin < 4
%             K11 = 1;
%             K22 = 1;
%             K33 = 1;
%         end


Nr = matrix(:,:,:,1);
Nt = matrix(:,:,:,2);
Np = matrix(:,:,:,3);

[dNxdx, dNxdy, dNxdz] = gradient(Nx, deltax, deltay, deltaz);
[d2Nxdxdx, d2Nxdxdy, d2Nxdxdz] = gradient(dNxdx,deltax,deltay,deltaz);
[~, d2Nxdydy, d2Nxdydz] = gradient(dNxdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nxdzdz] = gradient(dNxdz,deltax,deltay,deltaz); % 2 repeats

[dNydx, dNydy, dNydz] = gradient(Ny, deltax, deltay, deltaz);
[d2Nydxdx, d2Nydxdy, d2Nydxdz] = gradient(dNydx,deltax,deltay,deltaz);
[~, d2Nydydy, d2Nydydz] = gradient(dNydy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nydzdz] = gradient(dNydz,deltax,deltay,deltaz); % 2 repeats

[dNzdx, dNzdy, dNzdz] = gradient(Nz, deltax, deltay, deltaz);
[d2Nzdxdx, d2Nzdxdy, d2Nzdxdz] = gradient(dNzdx,deltax,deltay,deltaz);
[~, d2Nzdydy, d2Nzdydz] = gradient(dNzdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nzdzdz] = gradient(dNzdz,deltax,deltay,deltaz); % 2 repeats


ELx = (1/4).*K11.*(2.*d2\[Phi]dydz.*cos(\[Phi])+(-2).*d\[Phi]dx.*d\[Phi]dz.*cos(\[Phi])+(-2).* ...
  d2\[Phi]dydz.*cos(\[Theta]).^2.*cos(\[Phi])+2.*d\[Phi]dx.*d\[Phi]dz.*cos(\[Theta]).^2.*cos(\[Phi])+(-4).* ...
  d2\[Theta]dxdx.*cos(\[Theta]).^2.*cos(\[Phi]).^2+(-4).*d\[Theta]dy.*d\[Phi]dx.*cos(\[Theta]).^2.*cos(\[Phi]) ...
  .^2+(-4).*d\[Theta]dx.*d\[Phi]dy.*cos(\[Theta]).^2.*cos(\[Phi]).^2+(-4).*d2\[Theta]dzdz.*sin(\[Theta]) ...
  .^2+2.*d2\[Phi]dydz.*cos(\[Phi]).*sin(\[Theta]).^2+(-2).*d\[Phi]dx.*d\[Phi]dz.*cos(\[Phi]).*sin(\[Theta]) ...
  .^2+(-2).*d\[Theta]dz.^2.*sin(2.*\[Theta])+4.*d2\[Theta]dxdz.*cos(\[Phi]).*sin(2.*\[Theta])+2.* ...
  d\[Theta]dy.*d\[Phi]dz.*cos(\[Phi]).*sin(2.*\[Theta])+(-2).*d2\[Phi]dxdy.*cos(\[Phi]).^2.*sin(2.*\[Theta])+ ...
  2.*d\[Theta]dx.^2.*cos(\[Phi]).^2.*sin(2.*\[Theta])+2.*d\[Phi]dx.^2.*cos(\[Phi]).^2.*sin(2.*\[Theta])+ ...
  (-2).*d2\[Phi]dxdz.*sin(\[Phi])+(-2).*d\[Phi]dy.*d\[Phi]dz.*sin(\[Phi])+2.*d2\[Phi]dxdz.*cos(\[Theta]) ...
  .^2.*sin(\[Phi])+2.*d\[Phi]dy.*d\[Phi]dz.*cos(\[Theta]).^2.*sin(\[Phi])+(-2).*d2\[Phi]dxdz.*sin(\[Theta]) ...
  .^2.*sin(\[Phi])+(-2).*d\[Phi]dy.*d\[Phi]dz.*sin(\[Theta]).^2.*sin(\[Phi])+4.*d2\[Theta]dydz.*sin( ...
  2.*\[Theta]).*sin(\[Phi])+(-2).*d\[Theta]dx.*d\[Phi]dz.*sin(2.*\[Theta]).*sin(\[Phi])+(-4).*d2\[Theta]dydy.* ...
  cos(\[Theta]).^2.*sin(\[Phi]).^2+4.*d\[Theta]dy.*d\[Phi]dx.*cos(\[Theta]).^2.*sin(\[Phi]).^2+4.*d\[Theta]dx.* ...
  d\[Phi]dy.*cos(\[Theta]).^2.*sin(\[Phi]).^2+2.*d2\[Phi]dxdy.*sin(2.*\[Theta]).*sin(\[Phi]).^2+2.* ...
  d\[Theta]dy.^2.*sin(2.*\[Theta]).*sin(\[Phi]).^2+2.*d\[Phi]dy.^2.*sin(2.*\[Theta]).*sin(\[Phi]).^2+2.* ...
  d\[Theta]dz.*(2.*d\[Theta]dx.*cos(\[Theta]).^2.*cos(\[Phi])+(-2).*d\[Theta]dx.*cos(\[Phi]).*sin(\[Theta]).^2+ ...
  d\[Phi]dy.*cos(\[Phi]).*sin(2.*\[Theta])+2.*d\[Theta]dy.*cos(2.*\[Theta]).*sin(\[Phi])+(-1).*d\[Phi]dx.* ...
  sin(2.*\[Theta]).*sin(\[Phi]))+(-4).*d2\[Theta]dxdy.*cos(\[Theta]).^2.*sin(2.*\[Phi])+4.*d\[Theta]dx.* ...
  d\[Phi]dx.*cos(\[Theta]).^2.*sin(2.*\[Phi])+(-4).*d\[Theta]dy.*d\[Phi]dy.*cos(\[Theta]).^2.*sin(2.*\[Phi])+ ...
  d2\[Phi]dxdx.*sin(2.*\[Theta]).*sin(2.*\[Phi])+(-1).*d2\[Phi]dydy.*sin(2.*\[Theta]).*sin(2.*\[Phi])+ ...
  2.*d\[Theta]dx.*d\[Theta]dy.*sin(2.*\[Theta]).*sin(2.*\[Phi])+2.*d\[Phi]dx.*d\[Phi]dy.*sin(2.*\[Theta]).*sin( ...
  2.*\[Phi]))+(1/4).*K22.*((-4).*d2\[Theta]dydy.*cos(\[Phi]).^2+4.*d\[Theta]dx.*d\[Phi]dy.*cos(\[Phi]) ...
  .^2+(-4).*d2\[Phi]dydz.*cos(\[Phi]).*sin(\[Theta]).^2+8.*d\[Phi]dz.^2.*cos(\[Theta]).*sin(\[Theta]) ...
  .^3+2.*d2\[Phi]dxdy.*cos(\[Phi]).^2.*sin(2.*\[Theta])+(-2).*d\[Phi]dx.^2.*cos(\[Phi]).^2.* ...
  sin(2.*\[Theta])+2.*d\[Phi]dy.^2.*cos(\[Phi]).^2.*sin(2.*\[Theta])+d\[Phi]dx.^2.*cos(\[Phi]).^2.* ...
  sin(4.*\[Theta])+4.*d2\[Phi]dxdz.*sin(\[Theta]).^2.*sin(\[Phi])+(-4).*d2\[Theta]dxdx.*sin(\[Phi]).^2+( ...
  -4).*d\[Theta]dx.*d\[Phi]dy.*sin(\[Phi]).^2+(-2).*d2\[Phi]dxdy.*sin(2.*\[Theta]).*sin(\[Phi]).^2+2.* ...
  d\[Phi]dx.^2.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(-2).*d\[Phi]dy.^2.*sin(2.*\[Theta]).*sin(\[Phi]).^2+ ...
  d\[Phi]dy.^2.*sin(4.*\[Theta]).*sin(\[Phi]).^2+(-8).*d\[Phi]dz.*cos(2.*\[Theta]).*sin(\[Theta]).^2.*( ...
  d\[Phi]dx.*cos(\[Phi])+d\[Phi]dy.*sin(\[Phi]))+4.*d2\[Theta]dxdy.*sin(2.*\[Phi])+(-4).*d\[Theta]dx.* ...
  d\[Phi]dx.*sin(2.*\[Phi])+(-1).*d2\[Phi]dxdx.*sin(2.*\[Theta]).*sin(2.*\[Phi])+d2\[Phi]dydy.*sin( ...
  2.*\[Theta]).*sin(2.*\[Phi])+(-4).*d\[Phi]dx.*d\[Phi]dy.*sin(2.*\[Theta]).*sin(2.*\[Phi])+d\[Phi]dx.* ...
  d\[Phi]dy.*sin(4.*\[Theta]).*sin(2.*\[Phi])+4.*d\[Theta]dy.*(d\[Phi]dx.*cos(2.*\[Phi])+d\[Phi]dy.*sin(2.* ...
  \[Phi])))+K33.*((-1/2).*d2\[Theta]dzdz+(-1/2).*d2\[Theta]dzdz.*cos(2.*\[Theta])+(-1).*d\[Theta]dx.* ...
  d\[Theta]dz.*cos(2.*\[Theta]).*cos(\[Phi])+(-1).*d2\[Theta]dxdx.*cos(\[Phi]).^2.*sin(\[Theta]).^2+(-1).* ...
  d\[Theta]dy.*d\[Phi]dx.*cos(\[Phi]).^2.*sin(\[Theta]).^2+(-1).*d\[Theta]dx.*d\[Phi]dy.*cos(\[Phi]).^2.*sin( ...
  \[Theta]).^2+d\[Theta]dz.^2.*sin(2.*\[Theta])+(-1).*d2\[Theta]dxdz.*cos(\[Phi]).*sin(2.*\[Theta])+(-1/2).* ...
  d\[Theta]dy.*d\[Phi]dz.*cos(\[Phi]).*sin(2.*\[Theta])+(-1).*d\[Theta]dx.^2.*cos(\[Phi]).^2.*sin(2.*\[Theta])+ ...
  (-1).*d\[Theta]dy.*d\[Theta]dz.*cos(2.*\[Theta]).*sin(\[Phi])+(-1).*d2\[Theta]dydz.*sin(2.*\[Theta]).*sin( ...
  \[Phi])+(1/2).*d\[Theta]dx.*d\[Phi]dz.*sin(2.*\[Theta]).*sin(\[Phi])+(-1).*d2\[Theta]dydy.*sin(\[Theta]).^2.* ...
  sin(\[Phi]).^2+d\[Theta]dy.*d\[Phi]dx.*sin(\[Theta]).^2.*sin(\[Phi]).^2+d\[Theta]dx.*d\[Phi]dy.*sin(\[Theta]).^2.* ...
  sin(\[Phi]).^2+(-1).*d\[Theta]dy.^2.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(-1/2).*d\[Theta]dz.*( ...
  d\[Phi]dy.*cos(\[Phi]).*sin(2.*\[Theta])+2.*d\[Theta]dy.*cos(2.*\[Theta]).*sin(\[Phi]))+(-1/2).*d\[Theta]dz.* ...
  (2.*d\[Theta]dx.*cos(2.*\[Theta]).*cos(\[Phi])+(-1).*d\[Phi]dx.*sin(2.*\[Theta]).*sin(\[Phi]))+(-1).* ...
  d2\[Theta]dxdy.*sin(\[Theta]).^2.*sin(2.*\[Phi])+d\[Theta]dx.*d\[Phi]dx.*sin(\[Theta]).^2.*sin(2.*\[Phi])+( ...
  -1).*d\[Theta]dy.*d\[Phi]dy.*sin(\[Theta]).^2.*sin(2.*\[Phi])+(-1).*d\[Theta]dx.*d\[Theta]dy.*sin(2.*\[Theta]) ...
  .*sin(2.*\[Phi])+(1/32).*(32.*sin(\[Theta]).^2.*((-1).*d\[Theta]dz.*sin(\[Theta])+cos(\[Theta]).*( ...
  d\[Theta]dx.*cos(\[Phi])+d\[Theta]dy.*sin(\[Phi]))).*(d\[Theta]dz.*cos(\[Theta])+sin(\[Theta]).*(d\[Theta]dx.*cos(\[Phi])+ ...
  d\[Theta]dy.*sin(\[Phi])))+32.*cos(\[Theta]).*sin(\[Theta]).*(d\[Theta]dz.*cos(\[Theta])+sin(\[Theta]).*(d\[Theta]dx.* ...
  cos(\[Phi])+d\[Theta]dy.*sin(\[Phi]))).^2+(-4).*(4.*d\[Theta]dz.*cos(\[Theta]).^2.*cos(\[Phi])+2.* ...
  d\[Theta]dx.*sin(2.*\[Theta])+(-2).*d\[Phi]dz.*sin(2.*\[Theta]).*sin(\[Phi])+(-4).*d\[Phi]dy.*sin(\[Theta]) ...
  .^2.*sin(\[Phi]).^2+(-2).*d\[Theta]dx.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(-2).*d\[Phi]dx.*sin(\[Theta]) ...
  .^2.*sin(2.*\[Phi])+d\[Theta]dy.*sin(2.*\[Theta]).*sin(2.*\[Phi])).*((-2).*d\[Theta]dx.*cos(2.*\[Theta]) ...
  +2.*d\[Theta]dz.*cos(\[Phi]).*sin(2.*\[Theta])+2.*d\[Phi]dz.*cos(2.*\[Theta]).*sin(\[Phi])+2.*d\[Theta]dx.* ...
  cos(2.*\[Theta]).*sin(\[Phi]).^2+2.*d\[Phi]dy.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(-1).*d\[Theta]dy.* ...
  cos(2.*\[Theta]).*sin(2.*\[Phi])+d\[Phi]dx.*sin(2.*\[Theta]).*sin(2.*\[Phi]))+2.*(4.*d\[Phi]dx.*cos( ...
  \[Phi]).^2.*sin(\[Theta]).^2+2.*d\[Theta]dy.*sin(2.*\[Theta])+2.*d\[Phi]dz.*cos(\[Phi]).*sin(2.*\[Theta])+( ...
  -2).*d\[Theta]dy.*cos(\[Phi]).^2.*sin(2.*\[Theta])+4.*d\[Theta]dz.*cos(\[Theta]).^2.*sin(\[Phi])+2.* ...
  d\[Phi]dy.*sin(\[Theta]).^2.*sin(2.*\[Phi])+d\[Theta]dx.*sin(2.*\[Theta]).*sin(2.*\[Phi])).*(4.*d\[Theta]dy.* ...
  cos(2.*\[Theta])+4.*d\[Phi]dz.*cos(2.*\[Theta]).*cos(\[Phi])+(-4).*d\[Theta]dy.*cos(2.*\[Theta]).*cos(\[Phi]) ...
  .^2+4.*d\[Phi]dx.*cos(\[Phi]).^2.*sin(2.*\[Theta])+(-4).*d\[Theta]dz.*sin(2.*\[Theta]).*sin(\[Phi])+ ...
  2.*d\[Theta]dx.*cos(2.*\[Theta]).*sin(2.*\[Phi])+2.*d\[Phi]dy.*sin(2.*\[Theta]).*sin(2.*\[Phi]))));


ELy = (1/8).*K22.*((-4).*d\[Theta]dx.*d\[Theta]dy.*cos(2.*\[Theta])+(-8).*d\[Theta]dx.*d\[Theta]dy.*cos(\[Phi]) ...
  .^2+8.*d\[Theta]dx.*d\[Theta]dy.*cos(2.*\[Theta]).*cos(\[Phi]).^2+4.*d\[Theta]dx.*d\[Theta]dy.*cos(2.*\[Theta]).* ...
  cos(2.*\[Phi])+(-8).*d2\[Theta]dydz.*cos(\[Phi]).*sin(\[Theta]).^2+8.*d\[Theta]dx.*d\[Phi]dz.*cos(\[Phi]).* ...
  sin(\[Theta]).^2+16.*d\[Theta]dx.*d\[Phi]dz.*cos(2.*\[Theta]).*cos(\[Phi]).*sin(\[Theta]).^2+16.* ...
  d2\[Phi]dxdz.*cos(\[Theta]).*cos(\[Phi]).*sin(\[Theta]).^3+8.*d\[Phi]dy.*d\[Phi]dz.*cos(\[Theta]).*cos(\[Phi]).* ...
  sin(\[Theta]).^3+(-8).*d2\[Phi]dzdz.*sin(\[Theta]).^4+4.*d2\[Theta]dxdy.*cos(\[Phi]).^2.*sin(2.* ...
  \[Theta])+(-2).*d2\[Phi]dxdx.*cos(\[Phi]).^2.*sin(2.*\[Theta]).^2+(-2).*d\[Phi]dx.*d\[Phi]dy.*cos(\[Phi]) ...
  .^2.*sin(2.*\[Theta]).^2+(-4).*d\[Theta]dx.*d\[Phi]dx.*cos(\[Phi]).^2.*sin(4.*\[Theta])+8.* ...
  d2\[Theta]dxdz.*sin(\[Theta]).^2.*sin(\[Phi])+8.*d\[Theta]dy.*d\[Phi]dz.*sin(\[Theta]).^2.*sin(\[Phi])+16.* ...
  d\[Theta]dy.*d\[Phi]dz.*cos(2.*\[Theta]).*sin(\[Theta]).^2.*sin(\[Phi])+16.*d2\[Phi]dydz.*cos(\[Theta]).*sin( ...
  \[Theta]).^3.*sin(\[Phi])+(-8).*d\[Phi]dx.*d\[Phi]dz.*cos(\[Theta]).*sin(\[Theta]).^3.*sin(\[Phi])+8.* ...
  d\[Theta]dx.*d\[Theta]dy.*sin(\[Phi]).^2+(-4).*d2\[Theta]dxdy.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(-2).* ...
  d2\[Phi]dydy.*sin(2.*\[Theta]).^2.*sin(\[Phi]).^2+2.*d\[Phi]dx.*d\[Phi]dy.*sin(2.*\[Theta]).^2.*sin( ...
  \[Phi]).^2+(-4).*d\[Theta]dy.*d\[Phi]dy.*sin(4.*\[Theta]).*sin(\[Phi]).^2+(-2).*d\[Theta]dz.*(16.* ...
  d\[Phi]dz.*cos(\[Theta]).*sin(\[Theta]).^3+(-2).*(2.*d\[Phi]dx.*cos(2.*\[Theta]).*cos(\[Phi]).*sin(\[Theta]) ...
  .^2+(-2).*d\[Theta]dy.*cos(\[Phi]).*sin(2.*\[Theta])+d\[Phi]dx.*cos(\[Phi]).*sin(2.*\[Theta]).^2+2.* ...
  d\[Phi]dy.*(1+2.*cos(2.*\[Theta])).*sin(\[Theta]).^2.*sin(\[Phi])+2.*d\[Theta]dx.*sin(2.*\[Theta]).*sin( ...
  \[Phi])))+4.*d\[Theta]dx.^2.*sin(2.*\[Phi])+(-4).*d\[Theta]dy.^2.*sin(2.*\[Phi])+(-4).* ...
  d\[Theta]dx.^2.*cos(2.*\[Theta]).*sin(2.*\[Phi])+4.*d\[Theta]dy.^2.*cos(2.*\[Theta]).*sin(2.*\[Phi])+( ...
  -2).*d2\[Theta]dxdx.*sin(2.*\[Theta]).*sin(2.*\[Phi])+2.*d2\[Theta]dydy.*sin(2.*\[Theta]).*sin(2.* ...
  \[Phi])+(-2).*d2\[Phi]dxdy.*sin(2.*\[Theta]).^2.*sin(2.*\[Phi])+d\[Phi]dx.^2.*sin(2.*\[Theta]).^2.* ...
  sin(2.*\[Phi])+(-1).*d\[Phi]dy.^2.*sin(2.*\[Theta]).^2.*sin(2.*\[Phi])+(-2).*d\[Theta]dy.* ...
  d\[Phi]dx.*sin(4.*\[Theta]).*sin(2.*\[Phi])+(-2).*d\[Theta]dx.*d\[Phi]dy.*sin(4.*\[Theta]).*sin(2.*\[Phi])) ...
  +(-1/2).*K11.*sin(\[Theta]).*(2.*d\[Theta]dx.*d\[Phi]dx.*cos(\[Theta])+2.*d2\[Theta]dxdy.*cos(\[Theta]).* ...
  cos(\[Phi]).^2+(-2).*d\[Theta]dx.*d\[Phi]dx.*cos(\[Theta]).*cos(\[Phi]).^2+d2\[Phi]dxdx.*sin(\[Theta])+ ...
  d2\[Phi]dydy.*sin(\[Theta])+(-2).*d2\[Theta]dydz.*cos(\[Phi]).*sin(\[Theta])+(-1).*d2\[Phi]dxdx.*cos( ...
  \[Phi]).^2.*sin(\[Theta])+d2\[Phi]dydy.*cos(\[Phi]).^2.*sin(\[Theta])+(-2).*d\[Phi]dx.*d\[Phi]dy.*cos(\[Phi]) ...
  .^2.*sin(\[Theta])+2.*d2\[Theta]dxdz.*sin(\[Theta]).*sin(\[Phi])+(-2).*d2\[Theta]dxdy.*cos(\[Theta]).*sin( ...
  \[Phi]).^2+2.*d\[Theta]dx.*d\[Phi]dx.*cos(\[Theta]).*sin(\[Phi]).^2+d2\[Phi]dxdx.*sin(\[Theta]).*sin(\[Phi]).^2+ ...
  (-1).*d2\[Phi]dydy.*sin(\[Theta]).*sin(\[Phi]).^2+2.*d\[Phi]dx.*d\[Phi]dy.*sin(\[Theta]).*sin(\[Phi]).^2+ ...
  (-2).*d\[Theta]dz.*cos(\[Theta]).*(d\[Theta]dy.*cos(\[Phi])+(-1).*d\[Theta]dx.*sin(\[Phi]))+(-1).* ...
  d2\[Theta]dxdx.*cos(\[Theta]).*sin(2.*\[Phi])+d2\[Theta]dydy.*cos(\[Theta]).*sin(2.*\[Phi])+(-2).*d\[Theta]dx.* ...
  d\[Phi]dy.*cos(\[Theta]).*sin(2.*\[Phi])+(-2).*d2\[Phi]dxdy.*sin(\[Theta]).*sin(2.*\[Phi])+d\[Theta]dx.^2.* ...
  sin(\[Theta]).*sin(2.*\[Phi])+(-1).*d\[Theta]dy.^2.*sin(\[Theta]).*sin(2.*\[Phi])+d\[Phi]dx.^2.*sin(\[Theta]) ...
  .*sin(2.*\[Phi])+(-1).*d\[Phi]dy.^2.*sin(\[Theta]).*sin(2.*\[Phi])+d\[Theta]dy.*(4.*d\[Phi]dy.*cos( ...
  \[Theta]).*cos(\[Phi]).^2+(-2).*d\[Theta]dx.*cos(2.*\[Phi]).*sin(\[Theta])+(-2).*d\[Phi]dx.*cos(\[Theta]).* ...
  sin(2.*\[Phi])))+K33.*((-1/2).*d2\[Phi]dzdz.*sin(\[Theta]).^2+(-1/2).*d2\[Phi]dzdz.*cos( ...
  2.*\[Theta]).*sin(\[Theta]).^2+(-2).*d\[Theta]dz.*d\[Phi]dx.*cos(\[Theta]).^2.*cos(\[Phi]).*sin(\[Theta]).^2+( ...
  -2).*d2\[Phi]dxdz.*cos(\[Theta]).*cos(\[Phi]).*sin(\[Theta]).^3+(-1).*d\[Phi]dy.*d\[Phi]dz.*cos(\[Theta]).* ...
  cos(\[Phi]).*sin(\[Theta]).^3+(-4).*d\[Theta]dx.*d\[Phi]dx.*cos(\[Theta]).*cos(\[Phi]).^2.*sin(\[Theta]).^3+( ...
  -1).*d2\[Phi]dxdx.*cos(\[Phi]).^2.*sin(\[Theta]).^4+(-2).*d\[Phi]dx.*d\[Phi]dy.*cos(\[Phi]).^2.* ...
  sin(\[Theta]).^4+(-1/2).*d\[Theta]dz.*d\[Phi]dz.*sin(2.*\[Theta])+(-1/4).*d\[Theta]dz.*d\[Phi]dz.*sin( ...
  4.*\[Theta])+(-2).*d2\[Phi]dydz.*cos(\[Theta]).*sin(\[Theta]).^3.*sin(\[Phi])+d\[Phi]dx.*d\[Phi]dz.*cos(\[Theta]) ...
  .*sin(\[Theta]).^3.*sin(\[Phi])+(-1/2).*d\[Theta]dz.*d\[Phi]dy.*sin(2.*\[Theta]).^2.*sin(\[Phi])+(-1) ...
  .*d2\[Phi]dydy.*sin(\[Theta]).^4.*sin(\[Phi]).^2+2.*d\[Phi]dx.*d\[Phi]dy.*sin(\[Theta]).^4.*sin(\[Phi]) ...
  .^2+(-1).*d\[Theta]dy.*d\[Phi]dy.*sin(2.*\[Theta]).*sin(\[Phi]).^2+(1/2).*d\[Theta]dy.*d\[Phi]dy.*sin( ...
  4.*\[Theta]).*sin(\[Phi]).^2+(-1).*d\[Phi]dz.*sin(\[Theta]).^2.*(d\[Phi]dy.*cos(\[Theta]).*cos(\[Phi]).* ...
  sin(\[Theta])+d\[Theta]dy.*(1+2.*cos(2.*\[Theta])).*sin(\[Phi]))+(1/2).*d\[Phi]dz.*sin(\[Theta]).^2.*(( ...
  -2).*d\[Theta]dx.*(1+2.*cos(2.*\[Theta])).*cos(\[Phi])+d\[Phi]dx.*sin(2.*\[Theta]).*sin(\[Phi]))+ ...
  d\[Theta]dz.*sin(\[Theta]).^2.*(d\[Phi]dz.*sin(2.*\[Theta])+(-1).*cos(2.*\[Theta]).*(d\[Phi]dx.*cos(\[Phi])+ ...
  d\[Phi]dy.*sin(\[Phi])))+(-2).*d\[Theta]dx.*d\[Phi]dy.*cos(\[Theta]).*sin(\[Theta]).^3.*sin(2.*\[Phi])+(-1) ...
  .*d2\[Phi]dxdy.*sin(\[Theta]).^4.*sin(2.*\[Phi])+d\[Phi]dx.^2.*sin(\[Theta]).^4.*sin(2.*\[Phi])+(-1) ...
  .*d\[Phi]dy.^2.*sin(\[Theta]).^4.*sin(2.*\[Phi])+(-1/2).*d\[Theta]dy.*d\[Phi]dx.*sin(2.*\[Theta]).* ...
  sin(2.*\[Phi])+(1/4).*d\[Theta]dy.*d\[Phi]dx.*sin(4.*\[Theta]).*sin(2.*\[Phi])+(1/32).*(32.* ...
  sin(\[Theta]).^3.*(d\[Theta]dy.*cos(\[Phi])+(-1).*d\[Theta]dx.*sin(\[Phi])).*(d\[Theta]dz.*cos(\[Theta])+sin(\[Theta]) ...
  .*(d\[Theta]dx.*cos(\[Phi])+d\[Theta]dy.*sin(\[Phi])))+4.*(4.*d\[Phi]dx.*cos(\[Phi]).^2.*sin(\[Theta]).^2+ ...
  2.*d\[Theta]dy.*sin(2.*\[Theta])+2.*d\[Phi]dz.*cos(\[Phi]).*sin(2.*\[Theta])+(-2).*d\[Theta]dy.*cos(\[Phi]) ...
  .^2.*sin(2.*\[Theta])+4.*d\[Theta]dz.*cos(\[Theta]).^2.*sin(\[Phi])+2.*d\[Phi]dy.*sin(\[Theta]).^2.*sin( ...
  2.*\[Phi])+d\[Theta]dx.*sin(2.*\[Theta]).*sin(2.*\[Phi])).*(2.*d\[Theta]dz.*cos(\[Theta]).^2.*cos(\[Phi])+2.* ...
  d\[Phi]dy.*cos(2.*\[Phi]).*sin(\[Theta]).^2+d\[Theta]dx.*cos(2.*\[Phi]).*sin(2.*\[Theta])+(-1).*d\[Phi]dz.* ...
  sin(2.*\[Theta]).*sin(\[Phi])+(-2).*d\[Phi]dx.*sin(\[Theta]).^2.*sin(2.*\[Phi])+d\[Theta]dy.*sin(2.*\[Theta]) ...
  .*sin(2.*\[Phi]))+(-4).*(2.*d\[Phi]dx.*cos(2.*\[Phi]).*sin(\[Theta]).^2+d\[Phi]dz.*cos(\[Phi]).* ...
  sin(2.*\[Theta])+(-1).*d\[Theta]dy.*cos(2.*\[Phi]).*sin(2.*\[Theta])+2.*d\[Theta]dz.*cos(\[Theta]).^2.* ...
  sin(\[Phi])+2.*d\[Phi]dy.*sin(\[Theta]).^2.*sin(2.*\[Phi])+d\[Theta]dx.*sin(2.*\[Theta]).*sin(2.*\[Phi])).* ...
  (4.*d\[Theta]dz.*cos(\[Theta]).^2.*cos(\[Phi])+2.*d\[Theta]dx.*sin(2.*\[Theta])+(-2).*d\[Phi]dz.*sin(2.* ...
  \[Theta]).*sin(\[Phi])+(-4).*d\[Phi]dy.*sin(\[Theta]).^2.*sin(\[Phi]).^2+(-2).*d\[Theta]dx.*sin(2.*\[Theta]) ...
  .*sin(\[Phi]).^2+(-2).*d\[Phi]dx.*sin(\[Theta]).^2.*sin(2.*\[Phi])+d\[Theta]dy.*sin(2.*\[Theta]).*sin( ...
  2.*\[Phi]))));


EL


return
end
