function [ ELx, ELy, ELz ] = EL_terms(matrix, K11, K22, K33, deltax, deltay, deltaz)
%%currently running the
%         if nargin < 7
%             deltax = 1;
%             deltay = 1;
%             deltaz = 1;
%         else if nargin < 4
%             K11 = 1;
%             K22 = 1;
%             K33 = 1;
%         end


Nx = matrix(:,:,:,1);
Ny = matrix(:,:,:,2);
Nz = matrix(:,:,:,3);

[dNxdx, dNxdy, dNxdz] = gradient(Nx, deltax, deltay, deltaz);
[d2Nxdxdx, d2Nxdxdy, d2Nxdxdz] = gradient(dNxdx,deltax,deltay,deltaz);
[~, d2Nxdydy, d2Nxdydz] = gradient(dNxdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nxdzdz] = gradient(dNxdz,deltax,deltay,deltaz); % 2 repeats

[dNydx, dNydy, dNydz] = gradient(Ny, deltax, deltay, deltaz);
[d2Nydxdx, d2Nydxdy, d2Nydxdz] = gradient(dNydx,deltax,deltay,deltaz);
[~, d2Nydydy, d2Nydydz] = gradient(dNydy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nydzdz] = gradient(dNydz,deltax,deltay,deltaz); % 2 repeats

[dNzdx, dNzdy, dNzdz] = gradient(Nz, deltax, deltay, deltaz);
[d2Nzdxdx, d2Nzdxdy, d2Nzdxdz] = gradient(dNzdx,deltax,deltay,deltaz);
[~, d2Nzdydy, d2Nzdydz] = gradient(dNzdy,deltax,deltay,deltaz); % 1 repeat
[~, ~, d2Nzdzdz] = gradient(dNzdz,deltax,deltay,deltaz); % 2 repeats

ELx = K22.*(2.*dNxdx.^2.*Nx+(-2).*dNxdy.^2.*Nx+(-2).*dNxdz.^2.*Nx+2.* ...
  dNxdz.*dNzdx.*Nx+2.*d2Nxdxdx.*Nx.^2+(-2).*d2Nxdydy.*Nx.^2+(-2).* ...
  d2Nxdzdz.*Nx.^2+2.*d2Nydxdy.*Nx.^2+2.*d2Nzdxdz.*Nx.^2+2.*dNydx.* ...
  dNydy.*Ny+(-2).*dNxdz.*dNydz.*Ny+dNydz.*dNzdx.*Ny+dNxdz.*dNzdy.* ...
  Ny+dNydx.*dNzdz.*Ny+4.*d2Nxdxdy.*Nx.*Ny+(-1).*d2Nydzdz.*Nx.*Ny+ ...
  d2Nzdydz.*Nx.*Ny+(-1).*d2Nxdzdz.*Ny.^2+2.*d2Nydxdy.*Ny.^2+ ...
  d2Nzdxdz.*Ny.^2+dNxdz.*dNydy.*Nz+dNydy.*dNzdx.*Nz+dNydx.*dNzdy.* ...
  Nz+2.*dNzdx.*dNzdz.*Nz+4.*d2Nxdxdz.*Nx.*Nz+d2Nydydz.*Nx.*Nz+(-1).* ...
  d2Nzdydy.*Nx.*Nz+2.*d2Nxdydz.*Ny.*Nz+d2Nydxdz.*Ny.*Nz+d2Nzdxdy.* ...
  Ny.*Nz+(-1).*d2Nxdydy.*Nz.^2+d2Nydxdy.*Nz.^2+2.*d2Nzdxdz.*Nz.^2+ ...
  2.*dNxdx.*(dNydy.*Nx+dNzdz.*Nx+dNxdy.*Ny+dNxdz.*Nz)+dNxdy.*(2.* ...
  dNydx.*Nx+dNzdz.*Ny+dNydz.*Nz+(-2).*dNzdy.*Nz))+K11.*((-2).* ...
  dNxdz.*dNzdx.*Nx+(-4).*d2Nxdxdx.*Nx.^2+(-2).*d2Nydxdy.*Nx.^2+(-2) ...
  .*d2Nzdxdz.*Nx.^2+(-1).*dNydx.^2.*Nx.^3+2.*dNxdz.*dNzdx.*Nx.^3+( ...
  -1).*dNzdx.^2.*Nx.^3+2.*d2Nxdxdx.*Nx.^4+(-2).*dNydx.*dNydy.*Ny+( ...
  -1).*dNydz.*dNzdx.*Ny+(-1).*dNxdz.*dNzdy.*Ny+(-1).*dNydx.*dNzdz.* ...
  Ny+(-4).*d2Nxdxdy.*Nx.*Ny+(-1).*d2Nydxdx.*Nx.*Ny+(-1).*d2Nydydy.* ...
  Nx.*Ny+(-1).*d2Nzdydz.*Nx.*Ny+dNydx.*dNydy.*Nx.^2.*Ny+dNydz.* ...
  dNzdx.*Nx.^2.*Ny+2.*dNxdz.*dNzdy.*Nx.^2.*Ny+(-1).*dNzdx.*dNzdy.* ...
  Nx.^2.*Ny+dNydx.*dNzdz.*Nx.^2.*Ny+4.*d2Nxdxdy.*Nx.^3.*Ny+ ...
  d2Nydxdx.*Nx.^3.*Ny+(-1).*d2Nxdxdx.*Ny.^2+(-1).*d2Nxdydy.*Ny.^2+( ...
  -2).*d2Nydxdy.*Ny.^2+(-1).*d2Nzdxdz.*Ny.^2+2.*dNxdy.^2.*Nx.*Ny.^2+ ...
  (-2).*dNydx.^2.*Nx.*Ny.^2+2.*dNydy.^2.*Nx.*Ny.^2+dNxdz.*dNzdx.* ...
  Nx.*Ny.^2+(-1).*dNzdx.^2.*Nx.*Ny.^2+dNydz.*dNzdy.*Nx.*Ny.^2+ ...
  dNydy.*dNzdz.*Nx.*Ny.^2+d2Nxdxdx.*Nx.^2.*Ny.^2+2.*d2Nxdydy.* ...
  Nx.^2.*Ny.^2+2.*d2Nydxdy.*Nx.^2.*Ny.^2+(-2).*dNydx.*dNydy.*Ny.^3+ ...
  dNxdz.*dNzdy.*Ny.^3+(-1).*dNzdx.*dNzdy.*Ny.^3+2.*d2Nxdxdy.*Nx.* ...
  Ny.^3+d2Nydydy.*Nx.*Ny.^3+d2Nxdydy.*Ny.^4+(-1).*dNxdz.*dNydy.*Nz+( ...
  -1).*dNydy.*dNzdx.*Nz+(-1).*dNydx.*dNzdy.*Nz+(-2).*dNxdz.*dNzdz.* ...
  Nz+(-2).*dNzdx.*dNzdz.*Nz+(-4).*d2Nxdxdz.*Nx.*Nz+(-1).*d2Nydydz.* ...
  Nx.*Nz+(-1).*d2Nzdxdx.*Nx.*Nz+(-1).*d2Nzdzdz.*Nx.*Nz+2.*dNxdz.* ...
  dNydy.*Nx.^2.*Nz+(-1).*dNydx.*dNydz.*Nx.^2.*Nz+dNydy.*dNzdx.* ...
  Nx.^2.*Nz+dNydx.*dNzdy.*Nx.^2.*Nz+4.*dNxdz.*dNzdz.*Nx.^2.*Nz+ ...
  dNzdx.*dNzdz.*Nx.^2.*Nz+4.*d2Nxdxdz.*Nx.^3.*Nz+d2Nzdxdx.*Nx.^3.* ...
  Nz+(-2).*d2Nxdydz.*Ny.*Nz+(-1).*d2Nydxdz.*Ny.*Nz+(-1).*d2Nzdxdy.* ...
  Ny.*Nz+2.*dNxdz.*dNydx.*Nx.*Ny.*Nz+2.*dNydy.*dNydz.*Nx.*Ny.*Nz+( ...
  -2).*dNydx.*dNzdx.*Nx.*Ny.*Nz+2.*dNydy.*dNzdy.*Nx.*Ny.*Nz+2.* ...
  dNydz.*dNzdz.*Nx.*Ny.*Nz+2.*dNzdy.*dNzdz.*Nx.*Ny.*Nz+4.*d2Nxdydz.* ...
  Nx.^2.*Ny.*Nz+2.*d2Nydxdz.*Nx.^2.*Ny.*Nz+2.*d2Nzdxdy.*Nx.^2.*Ny.* ...
  Nz+3.*dNxdz.*dNydy.*Ny.^2.*Nz+(-2).*dNydx.*dNydz.*Ny.^2.*Nz+(-1).* ...
  dNydy.*dNzdx.*Ny.^2.*Nz+(-1).*dNydx.*dNzdy.*Ny.^2.*Nz+2.*dNxdz.* ...
  dNzdz.*Ny.^2.*Nz+(-1).*dNzdx.*dNzdz.*Ny.^2.*Nz+2.*d2Nxdxdz.*Nx.* ...
  Ny.^2.*Nz+2.*d2Nydydz.*Nx.*Ny.^2.*Nz+d2Nzdydy.*Nx.*Ny.^2.*Nz+2.* ...
  d2Nxdydz.*Ny.^3.*Nz+(-1).*d2Nxdxdx.*Nz.^2+(-1).*d2Nxdzdz.*Nz.^2+( ...
  -1).*d2Nydxdy.*Nz.^2+(-2).*d2Nzdxdz.*Nz.^2+2.*dNxdz.^2.*Nx.*Nz.^2+ ...
  (-1).*dNydx.^2.*Nx.*Nz.^2+3.*dNxdz.*dNzdx.*Nx.*Nz.^2+(-2).* ...
  dNzdx.^2.*Nx.*Nz.^2+dNydz.*dNzdy.*Nx.*Nz.^2+dNydy.*dNzdz.*Nx.* ...
  Nz.^2+2.*dNzdz.^2.*Nx.*Nz.^2+d2Nxdxdx.*Nx.^2.*Nz.^2+2.*d2Nxdzdz.* ...
  Nx.^2.*Nz.^2+2.*d2Nzdxdz.*Nx.^2.*Nz.^2+(-1).*dNydx.*dNydy.*Ny.* ...
  Nz.^2+2.*dNxdz.*dNydz.*Ny.*Nz.^2+(-1).*dNydz.*dNzdx.*Ny.*Nz.^2+3.* ...
  dNxdz.*dNzdy.*Ny.*Nz.^2+(-2).*dNzdx.*dNzdy.*Ny.*Nz.^2+(-1).* ...
  dNydx.*dNzdz.*Ny.*Nz.^2+2.*d2Nxdxdy.*Nx.*Ny.*Nz.^2+d2Nydzdz.*Nx.* ...
  Ny.*Nz.^2+2.*d2Nzdydz.*Nx.*Ny.*Nz.^2+d2Nxdydy.*Ny.^2.*Nz.^2+ ...
  d2Nxdzdz.*Ny.^2.*Nz.^2+dNxdz.*dNydy.*Nz.^3+(-1).*dNydx.*dNydz.* ...
  Nz.^3+4.*dNxdz.*dNzdz.*Nz.^3+(-2).*dNzdx.*dNzdz.*Nz.^3+2.* ...
  d2Nxdxdz.*Nx.*Nz.^3+d2Nzdzdz.*Nx.*Nz.^3+2.*d2Nxdydz.*Ny.*Nz.^3+ ...
  d2Nxdzdz.*Nz.^4+dNxdx.^2.*Nx.*((-4)+4.*Nx.^2+Ny.^2+Nz.^2)+dNxdy.*( ...
  (-1).*dNzdz.*Ny+2.*dNzdz.*Nx.^2.*Ny+dNzdz.*Ny.^3+(-1).*dNydz.*Nz+ ...
  2.*dNydz.*Nx.^2.*Nz+4.*dNxdz.*Nx.*Ny.*Nz+2.*dNzdx.*Nx.*Ny.*Nz+3.* ...
  dNydz.*Ny.^2.*Nz+2.*dNzdy.*Ny.^2.*Nz+3.*dNzdz.*Ny.*Nz.^2+dNydz.* ...
  Nz.^3+2.*dNydy.*Ny.*((-1)+2.*Nx.^2+2.*Ny.^2+Nz.^2)+dNydx.*Nx.*(( ...
  -2)+2.*Nx.^2+3.*Ny.^2+Nz.^2))+dNxdx.*((-2).*dNxdy.*Ny+(-2).* ...
  dNydx.*Ny+6.*dNxdy.*Nx.^2.*Ny+2.*dNydx.*Nx.^2.*Ny+dNxdy.*Ny.^3+( ...
  -2).*dNxdz.*Nz+(-2).*dNzdx.*Nz+6.*dNxdz.*Nx.^2.*Nz+2.*dNzdx.* ...
  Nx.^2.*Nz+2.*dNydz.*Nx.*Ny.*Nz+2.*dNzdy.*Nx.*Ny.*Nz+dNxdz.*Ny.^2.* ...
  Nz+dNxdy.*Ny.*Nz.^2+dNxdz.*Nz.^3+dNydy.*Nx.*((-2)+2.*Nx.^2+3.* ...
  Ny.^2+Nz.^2)+dNzdz.*Nx.*((-2)+2.*Nx.^2+Ny.^2+3.*Nz.^2)))+K33.*( ...
  dNydx.^2.*Nx.^3+(-2).*dNxdz.*dNzdx.*Nx.^3+dNzdx.^2.*Nx.^3+(-2).* ...
  d2Nxdxdx.*Nx.^4+(-1).*dNydx.*dNydy.*Nx.^2.*Ny+(-1).*dNydz.*dNzdx.* ...
  Nx.^2.*Ny+(-2).*dNxdz.*dNzdy.*Nx.^2.*Ny+dNzdx.*dNzdy.*Nx.^2.*Ny+( ...
  -1).*dNydx.*dNzdz.*Nx.^2.*Ny+(-4).*d2Nxdxdy.*Nx.^3.*Ny+(-1).* ...
  d2Nydxdx.*Nx.^3.*Ny+(-2).*dNxdy.^2.*Nx.*Ny.^2+2.*dNydx.^2.*Nx.* ...
  Ny.^2+(-2).*dNydy.^2.*Nx.*Ny.^2+(-1).*dNxdz.*dNzdx.*Nx.*Ny.^2+ ...
  dNzdx.^2.*Nx.*Ny.^2+(-1).*dNydz.*dNzdy.*Nx.*Ny.^2+(-1).*dNydy.* ...
  dNzdz.*Nx.*Ny.^2+(-1).*d2Nxdxdx.*Nx.^2.*Ny.^2+(-2).*d2Nxdydy.* ...
  Nx.^2.*Ny.^2+(-2).*d2Nydxdy.*Nx.^2.*Ny.^2+2.*dNydx.*dNydy.*Ny.^3+( ...
  -1).*dNxdz.*dNzdy.*Ny.^3+dNzdx.*dNzdy.*Ny.^3+(-2).*d2Nxdxdy.*Nx.* ...
  Ny.^3+(-1).*d2Nydydy.*Nx.*Ny.^3+(-1).*d2Nxdydy.*Ny.^4+(-2).* ...
  dNxdz.*dNydy.*Nx.^2.*Nz+dNydx.*dNydz.*Nx.^2.*Nz+(-1).*dNydy.* ...
  dNzdx.*Nx.^2.*Nz+(-1).*dNydx.*dNzdy.*Nx.^2.*Nz+(-4).*dNxdz.* ...
  dNzdz.*Nx.^2.*Nz+(-1).*dNzdx.*dNzdz.*Nx.^2.*Nz+(-4).*d2Nxdxdz.* ...
  Nx.^3.*Nz+(-1).*d2Nzdxdx.*Nx.^3.*Nz+(-2).*dNxdz.*dNydx.*Nx.*Ny.* ...
  Nz+(-2).*dNydy.*dNydz.*Nx.*Ny.*Nz+2.*dNydx.*dNzdx.*Nx.*Ny.*Nz+(-2) ...
  .*dNydy.*dNzdy.*Nx.*Ny.*Nz+(-2).*dNydz.*dNzdz.*Nx.*Ny.*Nz+(-2).* ...
  dNzdy.*dNzdz.*Nx.*Ny.*Nz+(-4).*d2Nxdydz.*Nx.^2.*Ny.*Nz+(-2).* ...
  d2Nydxdz.*Nx.^2.*Ny.*Nz+(-2).*d2Nzdxdy.*Nx.^2.*Ny.*Nz+(-3).* ...
  dNxdz.*dNydy.*Ny.^2.*Nz+2.*dNydx.*dNydz.*Ny.^2.*Nz+dNydy.*dNzdx.* ...
  Ny.^2.*Nz+dNydx.*dNzdy.*Ny.^2.*Nz+(-2).*dNxdz.*dNzdz.*Ny.^2.*Nz+ ...
  dNzdx.*dNzdz.*Ny.^2.*Nz+(-2).*d2Nxdxdz.*Nx.*Ny.^2.*Nz+(-2).* ...
  d2Nydydz.*Nx.*Ny.^2.*Nz+(-1).*d2Nzdydy.*Nx.*Ny.^2.*Nz+(-2).* ...
  d2Nxdydz.*Ny.^3.*Nz+(-2).*dNxdz.^2.*Nx.*Nz.^2+dNydx.^2.*Nx.*Nz.^2+ ...
  (-3).*dNxdz.*dNzdx.*Nx.*Nz.^2+2.*dNzdx.^2.*Nx.*Nz.^2+(-1).*dNydz.* ...
  dNzdy.*Nx.*Nz.^2+(-1).*dNydy.*dNzdz.*Nx.*Nz.^2+(-2).*dNzdz.^2.* ...
  Nx.*Nz.^2+(-1).*d2Nxdxdx.*Nx.^2.*Nz.^2+(-2).*d2Nxdzdz.*Nx.^2.* ...
  Nz.^2+(-2).*d2Nzdxdz.*Nx.^2.*Nz.^2+dNydx.*dNydy.*Ny.*Nz.^2+(-2).* ...
  dNxdz.*dNydz.*Ny.*Nz.^2+dNydz.*dNzdx.*Ny.*Nz.^2+(-3).*dNxdz.* ...
  dNzdy.*Ny.*Nz.^2+2.*dNzdx.*dNzdy.*Ny.*Nz.^2+dNydx.*dNzdz.*Ny.* ...
  Nz.^2+(-2).*d2Nxdxdy.*Nx.*Ny.*Nz.^2+(-1).*d2Nydzdz.*Nx.*Ny.*Nz.^2+ ...
  (-2).*d2Nzdydz.*Nx.*Ny.*Nz.^2+(-1).*d2Nxdydy.*Ny.^2.*Nz.^2+(-1).* ...
  d2Nxdzdz.*Ny.^2.*Nz.^2+(-1).*dNxdz.*dNydy.*Nz.^3+dNydx.*dNydz.* ...
  Nz.^3+(-4).*dNxdz.*dNzdz.*Nz.^3+2.*dNzdx.*dNzdz.*Nz.^3+(-2).* ...
  d2Nxdxdz.*Nx.*Nz.^3+(-1).*d2Nzdzdz.*Nx.*Nz.^3+(-2).*d2Nxdydz.*Ny.* ...
  Nz.^3+(-1).*d2Nxdzdz.*Nz.^4+(-1).*dNxdx.^2.*Nx.*(4.*Nx.^2+Ny.^2+ ...
  Nz.^2)+(-1).*dNxdy.*(2.*dNzdz.*Nx.^2.*Ny+dNzdz.*Ny.^3+2.*dNydz.* ...
  Nx.^2.*Nz+4.*dNxdz.*Nx.*Ny.*Nz+2.*dNzdx.*Nx.*Ny.*Nz+3.*dNydz.* ...
  Ny.^2.*Nz+2.*dNzdy.*Ny.^2.*Nz+3.*dNzdz.*Ny.*Nz.^2+dNydz.*Nz.^3+2.* ...
  dNydy.*Ny.*(2.*Nx.^2+2.*Ny.^2+Nz.^2)+dNydx.*Nx.*(2.*Nx.^2+3.* ...
  Ny.^2+Nz.^2))+(-1).*dNxdx.*(6.*dNxdy.*Nx.^2.*Ny+2.*dNydx.*Nx.^2.* ...
  Ny+dNxdy.*Ny.^3+6.*dNxdz.*Nx.^2.*Nz+2.*dNzdx.*Nx.^2.*Nz+2.*dNydz.* ...
  Nx.*Ny.*Nz+2.*dNzdy.*Nx.*Ny.*Nz+dNxdz.*Ny.^2.*Nz+dNxdy.*Ny.*Nz.^2+ ...
  dNxdz.*Nz.^3+dNydy.*Nx.*(2.*Nx.^2+3.*Ny.^2+Nz.^2)+dNzdz.*Nx.*(2.* ...
  Nx.^2+Ny.^2+3.*Nz.^2)));

ELy = K22.*((-2).*dNxdz.*dNydz.*Nx+dNydz.*dNzdx.*Nx+dNxdz.*dNzdy.*Nx+ ...
  dNxdy.*dNzdz.*Nx+2.*d2Nxdxdy.*Nx.^2+(-1).*d2Nydzdz.*Nx.^2+ ...
  d2Nzdydz.*Nx.^2+(-2).*dNydx.^2.*Ny+2.*dNydy.^2.*Ny+(-2).* ...
  dNydz.^2.*Ny+2.*dNydz.*dNzdy.*Ny+2.*dNydy.*dNzdz.*Ny+(-1).* ...
  d2Nxdzdz.*Nx.*Ny+4.*d2Nydxdy.*Nx.*Ny+d2Nzdxdz.*Nx.*Ny+2.* ...
  d2Nxdxdy.*Ny.^2+(-2).*d2Nydxdx.*Ny.^2+2.*d2Nydydy.*Ny.^2+(-2).* ...
  d2Nydzdz.*Ny.^2+2.*d2Nzdydz.*Ny.^2+2.*dNydy.*dNydz.*Nz+dNxdy.* ...
  dNzdx.*Nz+2.*dNzdy.*dNzdz.*Nz+d2Nxdydz.*Nx.*Nz+2.*d2Nydxdz.*Nx.* ...
  Nz+d2Nzdxdy.*Nx.*Nz+d2Nxdxdz.*Ny.*Nz+4.*d2Nydydz.*Ny.*Nz+(-1).* ...
  d2Nzdxdx.*Ny.*Nz+d2Nxdxdy.*Nz.^2+(-1).*d2Nydxdx.*Nz.^2+2.* ...
  d2Nzdydz.*Nz.^2+dNydx.*(2.*dNydy.*Nx+dNzdz.*Nx+2.*dNxdy.*Ny+ ...
  dNxdz.*Nz+(-2).*dNzdx.*Nz)+dNxdx.*(2.*dNxdy.*Nx+2.*dNydy.*Ny+( ...
  dNydz+dNzdy).*Nz))+K11.*((-2).*dNydx.*dNydy.*Nx+(-1).*dNydz.* ...
  dNzdx.*Nx+(-1).*dNxdz.*dNzdy.*Nx+(-1).*dNydx.*dNzdz.*Nx+(-2).* ...
  d2Nxdxdy.*Nx.^2+(-1).*d2Nydxdx.*Nx.^2+(-1).*d2Nydydy.*Nx.^2+(-1).* ...
  d2Nzdydz.*Nx.^2+dNydx.*dNydy.*Nx.^3+dNydz.*dNzdx.*Nx.^3+(-1).* ...
  dNzdx.*dNzdy.*Nx.^3+dNydx.*dNzdz.*Nx.^3+d2Nydxdx.*Nx.^4+(-4).* ...
  dNydy.^2.*Ny+(-2).*dNydz.*dNzdy.*Ny+(-2).*dNydy.*dNzdz.*Ny+(-1).* ...
  d2Nxdxdx.*Nx.*Ny+(-1).*d2Nxdydy.*Nx.*Ny+(-4).*d2Nydxdy.*Nx.*Ny+( ...
  -1).*d2Nzdxdz.*Nx.*Ny+2.*dNxdx.^2.*Nx.^2.*Ny+2.*dNydx.^2.*Nx.^2.* ...
  Ny+dNydy.^2.*Nx.^2.*Ny+dNxdz.*dNzdx.*Nx.^2.*Ny+dNydz.*dNzdy.* ...
  Nx.^2.*Ny+(-1).*dNzdy.^2.*Nx.^2.*Ny+dNydy.*dNzdz.*Nx.^2.*Ny+ ...
  d2Nxdxdx.*Nx.^3.*Ny+2.*d2Nydxdy.*Nx.^3.*Ny+(-2).*d2Nxdxdy.*Ny.^2+( ...
  -4).*d2Nydydy.*Ny.^2+(-2).*d2Nzdydz.*Ny.^2+6.*dNydx.*dNydy.*Nx.* ...
  Ny.^2+2.*dNydz.*dNzdx.*Nx.*Ny.^2+dNxdz.*dNzdy.*Nx.*Ny.^2+(-1).* ...
  dNzdx.*dNzdy.*Nx.*Ny.^2+2.*dNydx.*dNzdz.*Nx.*Ny.^2+2.*d2Nxdxdy.* ...
  Nx.^2.*Ny.^2+2.*d2Nydxdx.*Nx.^2.*Ny.^2+d2Nydydy.*Nx.^2.*Ny.^2+4.* ...
  dNydy.^2.*Ny.^3+2.*dNydz.*dNzdy.*Ny.^3+(-1).*dNzdy.^2.*Ny.^3+2.* ...
  dNydy.*dNzdz.*Ny.^3+d2Nxdydy.*Nx.*Ny.^3+4.*d2Nydxdy.*Nx.*Ny.^3+2.* ...
  d2Nydydy.*Ny.^4+(-1).*dNxdz.*dNydx.*Nz+(-2).*dNydy.*dNydz.*Nz+(-2) ...
  .*dNydy.*dNzdy.*Nz+(-2).*dNydz.*dNzdz.*Nz+(-2).*dNzdy.*dNzdz.*Nz+( ...
  -1).*d2Nxdydz.*Nx.*Nz+(-2).*d2Nydxdz.*Nx.*Nz+(-1).*d2Nzdxdy.*Nx.* ...
  Nz+3.*dNxdz.*dNydx.*Nx.^2.*Nz+dNydy.*dNydz.*Nx.^2.*Nz+2.*dNydx.* ...
  dNzdx.*Nx.^2.*Nz+2.*dNydz.*dNzdz.*Nx.^2.*Nz+(-1).*dNzdy.*dNzdz.* ...
  Nx.^2.*Nz+2.*d2Nydxdz.*Nx.^3.*Nz+(-1).*d2Nxdxdz.*Ny.*Nz+(-4).* ...
  d2Nydydz.*Ny.*Nz+(-1).*d2Nzdydy.*Ny.*Nz+(-1).*d2Nzdzdz.*Ny.*Nz+2.* ...
  dNxdz.*dNydy.*Nx.*Ny.*Nz+4.*dNydx.*dNydz.*Nx.*Ny.*Nz+2.*dNydy.* ...
  dNzdx.*Nx.*Ny.*Nz+2.*dNydx.*dNzdy.*Nx.*Ny.*Nz+2.*dNxdz.*dNzdz.* ...
  Nx.*Ny.*Nz+2.*dNzdx.*dNzdz.*Nx.*Ny.*Nz+2.*d2Nxdxdz.*Nx.^2.*Ny.*Nz+ ...
  2.*d2Nydydz.*Nx.^2.*Ny.*Nz+d2Nzdxdx.*Nx.^2.*Ny.*Nz+2.*dNxdz.* ...
  dNydx.*Ny.^2.*Nz+6.*dNydy.*dNydz.*Ny.^2.*Nz+2.*dNydy.*dNzdy.* ...
  Ny.^2.*Nz+4.*dNydz.*dNzdz.*Ny.^2.*Nz+dNzdy.*dNzdz.*Ny.^2.*Nz+2.* ...
  d2Nxdydz.*Nx.*Ny.^2.*Nz+4.*d2Nydxdz.*Nx.*Ny.^2.*Nz+2.*d2Nzdxdy.* ...
  Nx.*Ny.^2.*Nz+4.*d2Nydydz.*Ny.^3.*Nz+d2Nzdydy.*Ny.^3.*Nz+(-1).* ...
  d2Nxdxdy.*Nz.^2+(-1).*d2Nydydy.*Nz.^2+(-1).*d2Nydzdz.*Nz.^2+(-2).* ...
  d2Nzdydz.*Nz.^2+dNydx.*dNydy.*Nx.*Nz.^2+2.*dNxdz.*dNydz.*Nx.* ...
  Nz.^2+3.*dNydz.*dNzdx.*Nx.*Nz.^2+(-1).*dNxdz.*dNzdy.*Nx.*Nz.^2+( ...
  -2).*dNzdx.*dNzdy.*Nx.*Nz.^2+3.*dNydx.*dNzdz.*Nx.*Nz.^2+d2Nydxdx.* ...
  Nx.^2.*Nz.^2+d2Nydzdz.*Nx.^2.*Nz.^2+dNydy.^2.*Ny.*Nz.^2+2.* ...
  dNydz.^2.*Ny.*Nz.^2+dNxdz.*dNzdx.*Ny.*Nz.^2+3.*dNydz.*dNzdy.*Ny.* ...
  Nz.^2+(-2).*dNzdy.^2.*Ny.*Nz.^2+3.*dNydy.*dNzdz.*Ny.*Nz.^2+2.* ...
  dNzdz.^2.*Ny.*Nz.^2+d2Nxdzdz.*Nx.*Ny.*Nz.^2+2.*d2Nydxdy.*Nx.*Ny.* ...
  Nz.^2+2.*d2Nzdxdz.*Nx.*Ny.*Nz.^2+d2Nydydy.*Ny.^2.*Nz.^2+2.* ...
  d2Nydzdz.*Ny.^2.*Nz.^2+2.*d2Nzdydz.*Ny.^2.*Nz.^2+dNxdz.*dNydx.* ...
  Nz.^3+dNydy.*dNydz.*Nz.^3+4.*dNydz.*dNzdz.*Nz.^3+(-2).*dNzdy.* ...
  dNzdz.*Nz.^3+2.*d2Nydxdz.*Nx.*Nz.^3+2.*d2Nydydz.*Ny.*Nz.^3+ ...
  d2Nzdzdz.*Ny.*Nz.^3+d2Nydzdz.*Nz.^4+(-1).*dNxdy.^2.*Ny.*(2.*Nx.^2+ ...
  Ny.^2+Nz.^2)+dNxdy.*((-2).*dNydx.*Ny+3.*dNydx.*Nx.^2.*Ny+2.* ...
  dNydx.*Ny.^3+2.*dNydy.*Nx.*((-1)+Ny.^2)+(-1).*dNzdx.*Nz+(-2).* ...
  dNxdz.*Nx.^2.*Nz+(-1).*dNzdx.*Nx.^2.*Nz+2.*dNydz.*Nx.*Ny.*Nz+(-2) ...
  .*dNzdy.*Nx.*Ny.*Nz+(-1).*dNxdz.*Ny.^2.*Nz+dNzdx.*Ny.^2.*Nz+ ...
  dNydx.*Ny.*Nz.^2+(-1).*dNxdz.*Nz.^3+dNzdz.*Nx.*((-1)+Ny.^2+(-1).* ...
  Nz.^2))+dNxdx.*((-2).*dNydy.*Ny+3.*dNydy.*Nx.^2.*Ny+dNzdz.*Nx.^2.* ...
  Ny+2.*dNydy.*Ny.^3+(-1).*dNydz.*Nz+(-1).*dNzdy.*Nz+3.*dNydz.* ...
  Nx.^2.*Nz+(-1).*dNzdy.*Nx.^2.*Nz+2.*dNxdz.*Nx.*Ny.*Nz+2.*dNzdx.* ...
  Nx.*Ny.*Nz+2.*dNydz.*Ny.^2.*Nz+dNzdy.*Ny.^2.*Nz+dNydy.*Ny.*Nz.^2+ ...
  dNzdz.*Ny.*Nz.^2+dNydz.*Nz.^3+(-1).*dNxdy.*Nx.*(2+2.*Nx.^2+(-1).* ...
  Ny.^2+Nz.^2)+2.*dNydx.*Nx.*((-1)+2.*Nx.^2+2.*Ny.^2+Nz.^2)))+K33.*( ...
  (-1).*dNydz.*dNzdx.*Nx.^3+dNzdx.*dNzdy.*Nx.^3+(-1).*d2Nydxdx.* ...
  Nx.^4+(-2).*dNxdx.^2.*Nx.^2.*Ny+2.*dNxdy.^2.*Nx.^2.*Ny+(-2).* ...
  dNydx.^2.*Nx.^2.*Ny+(-1).*dNydy.^2.*Nx.^2.*Ny+(-1).*dNxdz.*dNzdx.* ...
  Nx.^2.*Ny+(-1).*dNydz.*dNzdy.*Nx.^2.*Ny+dNzdy.^2.*Nx.^2.*Ny+(-1).* ...
  dNydy.*dNzdz.*Nx.^2.*Ny+(-1).*d2Nxdxdx.*Nx.^3.*Ny+(-2).*d2Nydxdy.* ...
  Nx.^3.*Ny+(-2).*dNxdy.*dNydy.*Nx.*Ny.^2+(-2).*dNydz.*dNzdx.*Nx.* ...
  Ny.^2+(-1).*dNxdz.*dNzdy.*Nx.*Ny.^2+dNzdx.*dNzdy.*Nx.*Ny.^2+(-1).* ...
  dNxdy.*dNzdz.*Nx.*Ny.^2+(-2).*d2Nxdxdy.*Nx.^2.*Ny.^2+(-2).* ...
  d2Nydxdx.*Nx.^2.*Ny.^2+(-1).*d2Nydydy.*Nx.^2.*Ny.^2+dNxdy.^2.* ...
  Ny.^3+(-4).*dNydy.^2.*Ny.^3+(-2).*dNydz.*dNzdy.*Ny.^3+dNzdy.^2.* ...
  Ny.^3+(-2).*dNydy.*dNzdz.*Ny.^3+(-1).*d2Nxdydy.*Nx.*Ny.^3+(-4).* ...
  d2Nydxdy.*Nx.*Ny.^3+(-2).*d2Nydydy.*Ny.^4+2.*dNxdy.*dNxdz.*Nx.^2.* ...
  Nz+(-1).*dNydy.*dNydz.*Nx.^2.*Nz+dNxdy.*dNzdx.*Nx.^2.*Nz+(-2).* ...
  dNydz.*dNzdz.*Nx.^2.*Nz+dNzdy.*dNzdz.*Nx.^2.*Nz+(-2).*d2Nydxdz.* ...
  Nx.^3.*Nz+(-2).*dNxdz.*dNydy.*Nx.*Ny.*Nz+(-2).*dNxdy.*dNydz.*Nx.* ...
  Ny.*Nz+(-2).*dNydy.*dNzdx.*Nx.*Ny.*Nz+2.*dNxdy.*dNzdy.*Nx.*Ny.*Nz+ ...
  (-2).*dNxdz.*dNzdz.*Nx.*Ny.*Nz+(-2).*dNzdx.*dNzdz.*Nx.*Ny.*Nz+(-2) ...
  .*d2Nxdxdz.*Nx.^2.*Ny.*Nz+(-2).*d2Nydydz.*Nx.^2.*Ny.*Nz+(-1).* ...
  d2Nzdxdx.*Nx.^2.*Ny.*Nz+dNxdy.*dNxdz.*Ny.^2.*Nz+(-6).*dNydy.* ...
  dNydz.*Ny.^2.*Nz+(-1).*dNxdy.*dNzdx.*Ny.^2.*Nz+(-2).*dNydy.* ...
  dNzdy.*Ny.^2.*Nz+(-4).*dNydz.*dNzdz.*Ny.^2.*Nz+(-1).*dNzdy.* ...
  dNzdz.*Ny.^2.*Nz+(-2).*d2Nxdydz.*Nx.*Ny.^2.*Nz+(-4).*d2Nydxdz.* ...
  Nx.*Ny.^2.*Nz+(-2).*d2Nzdxdy.*Nx.*Ny.^2.*Nz+(-4).*d2Nydydz.* ...
  Ny.^3.*Nz+(-1).*d2Nzdydy.*Ny.^3.*Nz+(-2).*dNxdz.*dNydz.*Nx.*Nz.^2+ ...
  (-3).*dNydz.*dNzdx.*Nx.*Nz.^2+dNxdz.*dNzdy.*Nx.*Nz.^2+2.*dNzdx.* ...
  dNzdy.*Nx.*Nz.^2+dNxdy.*dNzdz.*Nx.*Nz.^2+(-1).*d2Nydxdx.*Nx.^2.* ...
  Nz.^2+(-1).*d2Nydzdz.*Nx.^2.*Nz.^2+dNxdy.^2.*Ny.*Nz.^2+(-1).* ...
  dNydy.^2.*Ny.*Nz.^2+(-2).*dNydz.^2.*Ny.*Nz.^2+(-1).*dNxdz.*dNzdx.* ...
  Ny.*Nz.^2+(-3).*dNydz.*dNzdy.*Ny.*Nz.^2+2.*dNzdy.^2.*Ny.*Nz.^2+( ...
  -3).*dNydy.*dNzdz.*Ny.*Nz.^2+(-2).*dNzdz.^2.*Ny.*Nz.^2+(-1).* ...
  d2Nxdzdz.*Nx.*Ny.*Nz.^2+(-2).*d2Nydxdy.*Nx.*Ny.*Nz.^2+(-2).* ...
  d2Nzdxdz.*Nx.*Ny.*Nz.^2+(-1).*d2Nydydy.*Ny.^2.*Nz.^2+(-2).* ...
  d2Nydzdz.*Ny.^2.*Nz.^2+(-2).*d2Nzdydz.*Ny.^2.*Nz.^2+dNxdy.*dNxdz.* ...
  Nz.^3+(-1).*dNydy.*dNydz.*Nz.^3+(-4).*dNydz.*dNzdz.*Nz.^3+2.* ...
  dNzdy.*dNzdz.*Nz.^3+(-2).*d2Nydxdz.*Nx.*Nz.^3+(-2).*d2Nydydz.*Ny.* ...
  Nz.^3+(-1).*d2Nzdzdz.*Ny.*Nz.^3+(-1).*d2Nydzdz.*Nz.^4+(-1).* ...
  dNxdx.*(3.*dNydy.*Nx.^2.*Ny+dNzdz.*Nx.^2.*Ny+2.*dNydy.*Ny.^3+3.* ...
  dNydz.*Nx.^2.*Nz+(-1).*dNzdy.*Nx.^2.*Nz+2.*dNxdz.*Nx.*Ny.*Nz+2.* ...
  dNzdx.*Nx.*Ny.*Nz+2.*dNydz.*Ny.^2.*Nz+dNzdy.*Ny.^2.*Nz+dNydy.*Ny.* ...
  Nz.^2+dNzdz.*Ny.*Nz.^2+dNydz.*Nz.^3+dNxdy.*Nx.*((-2).*Nx.^2+Ny.^2+ ...
  (-1).*Nz.^2)+2.*dNydx.*Nx.*(2.*Nx.^2+2.*Ny.^2+Nz.^2))+(-1).* ...
  dNydx.*(3.*dNxdy.*Nx.^2.*Ny+2.*dNxdy.*Ny.^3+3.*dNxdz.*Nx.^2.*Nz+ ...
  2.*dNzdx.*Nx.^2.*Nz+4.*dNydz.*Nx.*Ny.*Nz+2.*dNzdy.*Nx.*Ny.*Nz+2.* ...
  dNxdz.*Ny.^2.*Nz+dNxdy.*Ny.*Nz.^2+dNxdz.*Nz.^3+dNydy.*Nx.*(Nx.^2+ ...
  6.*Ny.^2+Nz.^2)+dNzdz.*Nx.*(Nx.^2+2.*Ny.^2+3.*Nz.^2)));

ELz = K22.*(dNxdy.*dNydz.*Nx+dNydy.*dNzdx.*Nx+(-2).*dNxdy.*dNzdy.*Nx+ ...
  dNydx.*dNzdy.*Nx+2.*dNzdx.*dNzdz.*Nx+2.*d2Nxdxdz.*Nx.^2+d2Nydydz.* ...
  Nx.^2+(-1).*d2Nzdydy.*Nx.^2+2.*dNydy.*dNydz.*Ny+dNxdy.*dNzdx.*Ny+( ...
  -2).*dNydx.*dNzdx.*Ny+2.*dNzdy.*dNzdz.*Ny+d2Nxdydz.*Nx.*Ny+ ...
  d2Nydxdz.*Nx.*Ny+2.*d2Nzdxdy.*Nx.*Ny+d2Nxdxdz.*Ny.^2+2.*d2Nydydz.* ...
  Ny.^2+(-1).*d2Nzdxdx.*Ny.^2+(-2).*dNzdx.^2.*Nz+2.*dNydz.*dNzdy.* ...
  Nz+(-2).*dNzdy.^2.*Nz+2.*dNydy.*dNzdz.*Nz+2.*dNzdz.^2.*Nz+(-1).* ...
  d2Nxdydy.*Nx.*Nz+d2Nydxdy.*Nx.*Nz+4.*d2Nzdxdz.*Nx.*Nz+d2Nxdxdy.* ...
  Ny.*Nz+(-1).*d2Nydxdx.*Ny.*Nz+4.*d2Nzdydz.*Ny.*Nz+2.*d2Nxdxdz.* ...
  Nz.^2+2.*d2Nydydz.*Nz.^2+(-2).*d2Nzdxdx.*Nz.^2+(-2).*d2Nzdydy.* ...
  Nz.^2+2.*d2Nzdzdz.*Nz.^2+dNxdz.*(dNydy.*Nx+dNydx.*Ny+2.*dNzdx.*Nz) ...
  +dNxdx.*(2.*dNxdz.*Nx+dNydz.*Ny+dNzdy.*Ny+2.*dNzdz.*Nz))+K11.*(( ...
  -1).*dNxdy.*dNydz.*Nx+(-1).*dNydy.*dNzdx.*Nx+(-1).*dNydx.*dNzdy.* ...
  Nx+(-2).*dNzdx.*dNzdz.*Nx+(-2).*d2Nxdxdz.*Nx.^2+(-1).*d2Nydydz.* ...
  Nx.^2+(-1).*d2Nzdxdx.*Nx.^2+(-1).*d2Nzdzdz.*Nx.^2+(-1).*dNydx.* ...
  dNydz.*Nx.^3+dNydy.*dNzdx.*Nx.^3+dNydx.*dNzdy.*Nx.^3+dNzdx.* ...
  dNzdz.*Nx.^3+d2Nzdxdx.*Nx.^4+(-2).*dNydy.*dNydz.*Ny+(-1).*dNxdy.* ...
  dNzdx.*Ny+(-2).*dNydy.*dNzdy.*Ny+(-2).*dNydz.*dNzdz.*Ny+(-2).* ...
  dNzdy.*dNzdz.*Ny+(-1).*d2Nxdydz.*Nx.*Ny+(-1).*d2Nydxdz.*Nx.*Ny+( ...
  -2).*d2Nzdxdy.*Nx.*Ny+(-1).*dNydy.*dNydz.*Nx.^2.*Ny+3.*dNxdy.* ...
  dNzdx.*Nx.^2.*Ny+2.*dNydx.*dNzdx.*Nx.^2.*Ny+2.*dNydy.*dNzdy.* ...
  Nx.^2.*Ny+dNzdy.*dNzdz.*Nx.^2.*Ny+2.*d2Nzdxdy.*Nx.^3.*Ny+(-1).* ...
  d2Nxdxdz.*Ny.^2+(-2).*d2Nydydz.*Ny.^2+(-1).*d2Nzdydy.*Ny.^2+(-1).* ...
  d2Nzdzdz.*Ny.^2+(-1).*dNxdy.*dNydz.*Nx.*Ny.^2+(-2).*dNydx.*dNydz.* ...
  Nx.*Ny.^2+3.*dNydy.*dNzdx.*Nx.*Ny.^2+2.*dNxdy.*dNzdy.*Nx.*Ny.^2+ ...
  3.*dNydx.*dNzdy.*Nx.*Ny.^2+dNzdx.*dNzdz.*Nx.*Ny.^2+d2Nzdxdx.* ...
  Nx.^2.*Ny.^2+d2Nzdydy.*Nx.^2.*Ny.^2+(-2).*dNydy.*dNydz.*Ny.^3+ ...
  dNxdy.*dNzdx.*Ny.^3+4.*dNydy.*dNzdy.*Ny.^3+dNzdy.*dNzdz.*Ny.^3+2.* ...
  d2Nzdxdy.*Nx.*Ny.^3+d2Nzdydy.*Ny.^4+(-2).*dNydz.*dNzdy.*Nz+(-2).* ...
  dNydy.*dNzdz.*Nz+(-4).*dNzdz.^2.*Nz+(-1).*d2Nxdxdx.*Nx.*Nz+(-1).* ...
  d2Nxdzdz.*Nx.*Nz+(-1).*d2Nydxdy.*Nx.*Nz+(-4).*d2Nzdxdz.*Nx.*Nz+2.* ...
  dNxdx.^2.*Nx.^2.*Nz+dNxdy.*dNydx.*Nx.^2.*Nz+(-1).*dNydz.^2.* ...
  Nx.^2.*Nz+2.*dNzdx.^2.*Nx.^2.*Nz+dNydz.*dNzdy.*Nx.^2.*Nz+dNydy.* ...
  dNzdz.*Nx.^2.*Nz+dNzdz.^2.*Nx.^2.*Nz+d2Nxdxdx.*Nx.^3.*Nz+2.* ...
  d2Nzdxdz.*Nx.^3.*Nz+(-1).*d2Nxdxdy.*Ny.*Nz+(-1).*d2Nydydy.*Ny.*Nz+ ...
  (-1).*d2Nydzdz.*Ny.*Nz+(-4).*d2Nzdydz.*Ny.*Nz+2.*dNxdy.*dNydy.* ...
  Nx.*Ny.*Nz+2.*dNydx.*dNydy.*Nx.*Ny.*Nz+2.*dNydz.*dNzdx.*Nx.*Ny.* ...
  Nz+4.*dNzdx.*dNzdy.*Nx.*Ny.*Nz+2.*dNxdy.*dNzdz.*Nx.*Ny.*Nz+2.* ...
  dNydx.*dNzdz.*Nx.*Ny.*Nz+2.*d2Nxdxdy.*Nx.^2.*Ny.*Nz+d2Nydxdx.* ...
  Nx.^2.*Ny.*Nz+2.*d2Nzdydz.*Nx.^2.*Ny.*Nz+dNxdy.*dNydx.*Ny.^2.*Nz+ ...
  2.*dNydy.^2.*Ny.^2.*Nz+(-2).*dNydz.^2.*Ny.^2.*Nz+3.*dNydz.*dNzdy.* ...
  Ny.^2.*Nz+2.*dNzdy.^2.*Ny.^2.*Nz+3.*dNydy.*dNzdz.*Ny.^2.*Nz+ ...
  dNzdz.^2.*Ny.^2.*Nz+d2Nxdydy.*Nx.*Ny.^2.*Nz+2.*d2Nydxdy.*Nx.* ...
  Ny.^2.*Nz+2.*d2Nzdxdz.*Nx.*Ny.^2.*Nz+d2Nydydy.*Ny.^3.*Nz+2.* ...
  d2Nzdydz.*Ny.^3.*Nz+(-2).*d2Nxdxdz.*Nz.^2+(-2).*d2Nydydz.*Nz.^2+( ...
  -4).*d2Nzdzdz.*Nz.^2+dNxdy.*dNydz.*Nx.*Nz.^2+(-1).*dNydx.*dNydz.* ...
  Nx.*Nz.^2+2.*dNydy.*dNzdx.*Nx.*Nz.^2+2.*dNydx.*dNzdy.*Nx.*Nz.^2+ ...
  6.*dNzdx.*dNzdz.*Nx.*Nz.^2+2.*d2Nxdxdz.*Nx.^2.*Nz.^2+2.*d2Nzdxdx.* ...
  Nx.^2.*Nz.^2+d2Nzdzdz.*Nx.^2.*Nz.^2+dNydy.*dNydz.*Ny.*Nz.^2+2.* ...
  dNxdy.*dNzdx.*Ny.*Nz.^2+4.*dNydy.*dNzdy.*Ny.*Nz.^2+2.*dNydz.* ...
  dNzdz.*Ny.*Nz.^2+6.*dNzdy.*dNzdz.*Ny.*Nz.^2+2.*d2Nxdydz.*Nx.*Ny.* ...
  Nz.^2+2.*d2Nydxdz.*Nx.*Ny.*Nz.^2+4.*d2Nzdxdy.*Nx.*Ny.*Nz.^2+2.* ...
  d2Nydydz.*Ny.^2.*Nz.^2+2.*d2Nzdydy.*Ny.^2.*Nz.^2+d2Nzdzdz.*Ny.^2.* ...
  Nz.^2+(-1).*dNydz.^2.*Nz.^3+2.*dNydz.*dNzdy.*Nz.^3+2.*dNydy.* ...
  dNzdz.*Nz.^3+4.*dNzdz.^2.*Nz.^3+d2Nxdzdz.*Nx.*Nz.^3+4.*d2Nzdxdz.* ...
  Nx.*Nz.^3+d2Nydzdz.*Ny.*Nz.^3+4.*d2Nzdydz.*Ny.*Nz.^3+2.*d2Nzdzdz.* ...
  Nz.^4+(-1).*dNxdz.^2.*Nz.*(2.*Nx.^2+Ny.^2+Nz.^2)+(-1).*dNxdz.*( ...
  dNydx.*Ny+2.*dNxdy.*Nx.^2.*Ny+dNydx.*Nx.^2.*Ny+dNxdy.*Ny.^3+2.* ...
  dNzdx.*Nz+(-3).*dNzdx.*Nx.^2.*Nz+2.*dNydz.*Nx.*Ny.*Nz+(-2).* ...
  dNzdy.*Nx.*Ny.*Nz+(-1).*dNzdx.*Ny.^2.*Nz+dNxdy.*Ny.*Nz.^2+(-1).* ...
  dNydx.*Ny.*Nz.^2+(-2).*dNzdx.*Nz.^3+dNydy.*Nx.*(1+Ny.^2+(-1).* ...
  Nz.^2)+(-2).*dNzdz.*Nx.*((-1)+Nz.^2))+dNxdx.*((-1).*dNydz.*Ny+(-1) ...
  .*dNzdy.*Ny+(-1).*dNydz.*Nx.^2.*Ny+3.*dNzdy.*Nx.^2.*Ny+dNzdy.* ...
  Ny.^3+(-2).*dNzdz.*Nz+dNydy.*Nx.^2.*Nz+3.*dNzdz.*Nx.^2.*Nz+2.* ...
  dNxdy.*Nx.*Ny.*Nz+2.*dNydx.*Nx.*Ny.*Nz+dNydy.*Ny.^2.*Nz+dNzdz.* ...
  Ny.^2.*Nz+dNydz.*Ny.*Nz.^2+2.*dNzdy.*Ny.*Nz.^2+2.*dNzdz.*Nz.^3+( ...
  -1).*dNxdz.*Nx.*(2+2.*Nx.^2+Ny.^2+(-1).*Nz.^2)+2.*dNzdx.*Nx.*((-1) ...
  +2.*Nx.^2+Ny.^2+2.*Nz.^2)))+K33.*((-1).*dNydy.*dNzdx.*Nx.^3+(-1).* ...
  dNzdx.*dNzdz.*Nx.^3+(-1).*d2Nzdxdx.*Nx.^4+2.*dNxdy.*dNxdz.*Nx.^2.* ...
  Ny+dNydy.*dNydz.*Nx.^2.*Ny+(-3).*dNxdy.*dNzdx.*Nx.^2.*Ny+(-2).* ...
  dNydy.*dNzdy.*Nx.^2.*Ny+(-1).*dNzdy.*dNzdz.*Nx.^2.*Ny+(-2).* ...
  d2Nzdxdy.*Nx.^3.*Ny+dNxdz.*dNydy.*Nx.*Ny.^2+dNxdy.*dNydz.*Nx.* ...
  Ny.^2+(-3).*dNydy.*dNzdx.*Nx.*Ny.^2+(-2).*dNxdy.*dNzdy.*Nx.*Ny.^2+ ...
  (-1).*dNzdx.*dNzdz.*Nx.*Ny.^2+(-1).*d2Nzdxdx.*Nx.^2.*Ny.^2+(-1).* ...
  d2Nzdydy.*Nx.^2.*Ny.^2+dNxdy.*dNxdz.*Ny.^3+2.*dNydy.*dNydz.*Ny.^3+ ...
  (-1).*dNxdy.*dNzdx.*Ny.^3+(-4).*dNydy.*dNzdy.*Ny.^3+(-1).*dNzdy.* ...
  dNzdz.*Ny.^3+(-2).*d2Nzdxdy.*Nx.*Ny.^3+(-1).*d2Nzdydy.*Ny.^4+(-2) ...
  .*dNxdx.^2.*Nx.^2.*Nz+2.*dNxdz.^2.*Nx.^2.*Nz+dNydz.^2.*Nx.^2.*Nz+( ...
  -3).*dNxdz.*dNzdx.*Nx.^2.*Nz+(-2).*dNzdx.^2.*Nx.^2.*Nz+(-1).* ...
  dNydz.*dNzdy.*Nx.^2.*Nz+(-1).*dNydy.*dNzdz.*Nx.^2.*Nz+(-1).* ...
  dNzdz.^2.*Nx.^2.*Nz+(-1).*d2Nxdxdx.*Nx.^3.*Nz+(-2).*d2Nzdxdz.* ...
  Nx.^3.*Nz+(-2).*dNxdy.*dNydy.*Nx.*Ny.*Nz+2.*dNxdz.*dNydz.*Nx.*Ny.* ...
  Nz+(-2).*dNydz.*dNzdx.*Nx.*Ny.*Nz+(-2).*dNxdz.*dNzdy.*Nx.*Ny.*Nz+( ...
  -4).*dNzdx.*dNzdy.*Nx.*Ny.*Nz+(-2).*dNxdy.*dNzdz.*Nx.*Ny.*Nz+(-2) ...
  .*d2Nxdxdy.*Nx.^2.*Ny.*Nz+(-1).*d2Nydxdx.*Nx.^2.*Ny.*Nz+(-2).* ...
  d2Nzdydz.*Nx.^2.*Ny.*Nz+dNxdz.^2.*Ny.^2.*Nz+(-2).*dNydy.^2.* ...
  Ny.^2.*Nz+2.*dNydz.^2.*Ny.^2.*Nz+(-1).*dNxdz.*dNzdx.*Ny.^2.*Nz+( ...
  -3).*dNydz.*dNzdy.*Ny.^2.*Nz+(-2).*dNzdy.^2.*Ny.^2.*Nz+(-3).* ...
  dNydy.*dNzdz.*Ny.^2.*Nz+(-1).*dNzdz.^2.*Ny.^2.*Nz+(-1).*d2Nxdydy.* ...
  Nx.*Ny.^2.*Nz+(-2).*d2Nydxdy.*Nx.*Ny.^2.*Nz+(-2).*d2Nzdxdz.*Nx.* ...
  Ny.^2.*Nz+(-1).*d2Nydydy.*Ny.^3.*Nz+(-2).*d2Nzdydz.*Ny.^3.*Nz+(-1) ...
  .*dNxdz.*dNydy.*Nx.*Nz.^2+(-1).*dNxdy.*dNydz.*Nx.*Nz.^2+(-2).* ...
  dNydy.*dNzdx.*Nx.*Nz.^2+(-2).*dNxdz.*dNzdz.*Nx.*Nz.^2+(-6).* ...
  dNzdx.*dNzdz.*Nx.*Nz.^2+(-2).*d2Nxdxdz.*Nx.^2.*Nz.^2+(-2).* ...
  d2Nzdxdx.*Nx.^2.*Nz.^2+(-1).*d2Nzdzdz.*Nx.^2.*Nz.^2+dNxdy.*dNxdz.* ...
  Ny.*Nz.^2+(-1).*dNydy.*dNydz.*Ny.*Nz.^2+(-2).*dNxdy.*dNzdx.*Ny.* ...
  Nz.^2+(-4).*dNydy.*dNzdy.*Ny.*Nz.^2+(-2).*dNydz.*dNzdz.*Ny.*Nz.^2+ ...
  (-6).*dNzdy.*dNzdz.*Ny.*Nz.^2+(-2).*d2Nxdydz.*Nx.*Ny.*Nz.^2+(-2).* ...
  d2Nydxdz.*Nx.*Ny.*Nz.^2+(-4).*d2Nzdxdy.*Nx.*Ny.*Nz.^2+(-2).* ...
  d2Nydydz.*Ny.^2.*Nz.^2+(-2).*d2Nzdydy.*Ny.^2.*Nz.^2+(-1).* ...
  d2Nzdzdz.*Ny.^2.*Nz.^2+dNxdz.^2.*Nz.^3+dNydz.^2.*Nz.^3+(-2).* ...
  dNxdz.*dNzdx.*Nz.^3+(-2).*dNydz.*dNzdy.*Nz.^3+(-2).*dNydy.*dNzdz.* ...
  Nz.^3+(-4).*dNzdz.^2.*Nz.^3+(-1).*d2Nxdzdz.*Nx.*Nz.^3+(-4).* ...
  d2Nzdxdz.*Nx.*Nz.^3+(-1).*d2Nydzdz.*Ny.*Nz.^3+(-4).*d2Nzdydz.*Ny.* ...
  Nz.^3+(-2).*d2Nzdzdz.*Nz.^4+(-1).*dNxdx.*((-1).*dNydz.*Nx.^2.*Ny+ ...
  3.*dNzdy.*Nx.^2.*Ny+dNzdy.*Ny.^3+dNydy.*Nx.^2.*Nz+3.*dNzdz.* ...
  Nx.^2.*Nz+2.*dNxdy.*Nx.*Ny.*Nz+2.*dNydx.*Nx.*Ny.*Nz+dNydy.*Ny.^2.* ...
  Nz+dNzdz.*Ny.^2.*Nz+dNydz.*Ny.*Nz.^2+2.*dNzdy.*Ny.*Nz.^2+2.* ...
  dNzdz.*Nz.^3+dNxdz.*Nx.*((-2).*Nx.^2+(-1).*Ny.^2+Nz.^2)+2.*dNzdx.* ...
  Nx.*(2.*Nx.^2+Ny.^2+2.*Nz.^2))+(-1).*dNydx.*((-1).*dNxdz.*Nx.^2.* ...
  Ny+2.*dNzdx.*Nx.^2.*Ny+dNxdy.*Nx.^2.*Nz+2.*dNydy.*Nx.*Ny.*Nz+2.* ...
  dNzdz.*Nx.*Ny.*Nz+dNxdy.*Ny.^2.*Nz+dNxdz.*Ny.*Nz.^2+(-1).*dNydz.* ...
  Nx.*(Nx.^2+2.*Ny.^2+Nz.^2)+dNzdy.*Nx.*(Nx.^2+3.*Ny.^2+2.*Nz.^2)));

return
end

