function [ ELx, ELy ] = EL_terms(matrix, K11, K22, K33, deltax, deltay)

Nx = matrix(:,:,1);
Ny = matrix(:,:,2);

[dNxdx, dNxdy] = gradient(Nx, deltax, deltay);
[d2Nxdxdx, d2Nxdxdy] = gradient(dNxdx,deltax,deltay);
[~, d2Nxdydy] = gradient(dNxdy,deltax,deltay);

[dNydx, dNydy] = gradient(Ny, deltax, deltay);
[d2Nydxdx, d2Nydxdy] = gradient(dNydx,deltax,deltay);
[~, d2Nydydy] = gradient(dNydy,deltax,deltay);

%Oseen-Frank calculation:
% ELx = ((-1).*d2Nxdxdx+(-1).*d2Nydxdy).*K11+K33.*((-1).*d2Nxdydy+ ...
%   d2Nydxdy+(-1).*dNxdy.^2.*Nx+dNydx.^2.*Nx+(-2).*dNxdy.*dNydy.*Ny+ ...
%   2.*dNydx.*dNydy.*Ny);


% ELy = ((-1).*d2Nxdxdy+(-1).*d2Nydydy).*K11+K33.*(d2Nxdxdy+2.*dNxdx.*( ...
%   dNxdy+(-1).*dNydx).*Nx+(-1).*d2Nydxdx.*Nx.^2+dNxdy.^2.*Ny+(-1).* ...
%   dNydx.^2.*Ny+(-1).*d2Nydxdx.*Ny.^2);


%% 
%These are from the new generating notebook, seems like 

ELx = ((-1).*d2Nxdxdx+(-1).*d2Nydxdy).*K11+K33.*((dNxdy+(-1).*dNydx) ...
  .^2.*Nx+(-2).*(dNxdy+(-1).*dNydx).*(dNxdy.*Nx+dNydy.*Ny)+(-1).*( ...
  d2Nxdydy+(-1).*d2Nydxdy).*(Nx.^2+Ny.^2));



ELy = ((-1).*d2Nxdxdy+(-1).*d2Nydydy).*K11+K33.*((dNxdy+(-1).*dNydx) ...
 .^2.*Ny+2.*(dNxdy+(-1).*dNydx).*(dNxdx.*Nx+dNydx.*Ny)+(d2Nxdxdy+( ...
 -1).*d2Nydxdx).*(Nx.^2+Ny.^2));


%{
ELx = (-2).*Nx.*(dNxdy.*dNydx+dNxdx.*(2.*dNxdx+dNydy)+(2.*d2Nxdxdx+ ...
  d2Nydxdy).*Nx)+(-1).*(2.*(dNxdy+dNydx).*(dNxdx+dNydy)+(4.* ...
  d2Nxdxdy+d2Nydxdx+d2Nydydy).*Nx).*Ny+(-1).*(d2Nxdxdx+d2Nxdydy+2.* ...
  d2Nydxdy).*Ny.^2+2.*K22.*((d2Nxdxdx+(-1).*d2Nxdydy+d2Nydxdy).* ...
  Nx.^2+Nx.*(dNxdy.*((-1).*dNxdy+dNydx)+dNxdx.*(dNxdx+dNydy)+2.* ...
  d2Nxdxdy.*Ny)+Ny.*(dNxdx.*dNxdy+dNydx.*dNydy+d2Nydxdy.*Ny))+K33.*( ...
  (-2).*d2Nxdxdx.*Nx.^4+(-1).*Ny.^3.*((-2).*dNydx.*dNydy+dNxdy.*( ...
  dNxdx+4.*dNydy)+d2Nxdydy.*Ny)+(-1).*Nx.^3.*(2.*dNxdy.*dNydx+(-1).* ...
  dNydx.^2+2.*dNxdx.*(2.*dNxdx+dNydy)+(4.*d2Nxdxdy+d2Nydxdx).*Ny)+( ...
  -1).*Nx.^2.*Ny.*(dNydx.*(2.*dNxdx+dNydy)+dNxdy.*(6.*dNxdx+4.* ...
  dNydy)+(d2Nxdxdx+2.*(d2Nxdydy+d2Nydxdy)).*Ny)+(-1).*Nx.*Ny.^2.*(( ...
  2.*dNxdy+(-1).*dNydx).*(dNxdy+2.*dNydx)+(dNxdx+dNydy).*(dNxdx+2.* ...
  dNydy)+(2.*d2Nxdxdy+d2Nydydy).*Ny))+K11.*(2.*d2Nxdxdx.*Nx.^4+ ...
  Nx.^3.*(2.*dNxdy.*dNydx+(-1).*dNydx.^2+2.*dNxdx.*(2.*dNxdx+dNydy)+ ...
  (4.*d2Nxdxdy+d2Nydxdx).*Ny)+Nx.*((-2).*(dNxdy.*dNydx+dNxdx.*(2.* ...
  dNxdx+dNydy))+(-1).*(4.*d2Nxdxdy+d2Nydxdx+d2Nydydy).*Ny+((2.* ...
  dNxdy+(-1).*dNydx).*(dNxdy+2.*dNydx)+(dNxdx+dNydy).*(dNxdx+2.* ...
  dNydy)).*Ny.^2+(2.*d2Nxdxdy+d2Nydydy).*Ny.^3)+Nx.^2.*((-2).*(2.* ...
  d2Nxdxdx+d2Nydxdy)+Ny.*(dNydx.*(2.*dNxdx+dNydy)+dNxdy.*(6.*dNxdx+ ...
  4.*dNydy)+(d2Nxdxdx+2.*(d2Nxdydy+d2Nydxdy)).*Ny))+Ny.*((-2).* ...
  dNydx.*(dNxdx+dNydy)+(-1).*(d2Nxdxdx+d2Nxdydy+2.*d2Nydxdy).*Ny+( ...
  -2).*dNydx.*dNydy.*Ny.^2+d2Nxdydy.*Ny.^3+dNxdy.*(dNxdx.*((-2)+ ...
  Ny.^2)+dNydy.*((-2)+4.*Ny.^2))));

ELy = (-1).*(2.*d2Nxdxdy+d2Nydxdx+d2Nydydy).*Nx.^2+(-1).*Nx.*(2.*(dNxdy+ ...
  dNydx).*(dNxdx+dNydy)+(d2Nxdxdx+d2Nxdydy+4.*d2Nydxdy).*Ny)+(-2).* ...
  Ny.*(dNxdy.*dNydx+dNydy.*(dNxdx+2.*dNydy)+(d2Nxdxdy+2.*d2Nydydy).* ...
  Ny)+2.*K22.*(Nx.*(dNxdx.*dNxdy+dNydx.*dNydy+d2Nxdxdy.*Nx)+((dNxdy+ ...
  (-1).*dNydx).*dNydx+dNydy.*(dNxdx+dNydy)+2.*d2Nydxdy.*Nx).*Ny+( ...
  d2Nxdxdy+(-1).*d2Nydxdx+d2Nydydy).*Ny.^2)+K33.*((-1).*d2Nydxdx.* ...
  Nx.^4+Nx.^3.*(2.*dNxdx.*dNxdy+(-1).*dNydx.*(4.*dNxdx+dNydy)+(-1).* ...
  (d2Nxdxdx+2.*d2Nydxdy).*Ny)+(-1).*Nx.*Ny.^2.*(dNxdy.*(dNxdx+2.* ...
  dNydy)+2.*dNydx.*(2.*dNxdx+3.*dNydy)+(d2Nxdydy+4.*d2Nydxdy).*Ny)+( ...
  -1).*Nx.^2.*Ny.*((-1).*(dNxdy+(-2).*dNydx).*(2.*dNxdy+dNydx)+( ...
  dNxdx+dNydy).*(2.*dNxdx+dNydy)+(2.*(d2Nxdxdy+d2Nydxdx)+d2Nydydy).* ...
  Ny)+Ny.^3.*(dNxdy.^2+(-2).*dNxdy.*dNydx+(-2).*(dNydy.*(dNxdx+2.* ...
  dNydy)+d2Nydydy.*Ny)))+K11.*(d2Nydxdx.*Nx.^4+Nx.^3.*((-2).*dNxdx.* ...
  dNxdy+dNydx.*(4.*dNxdx+dNydy)+(d2Nxdxdx+2.*d2Nydxdy).*Ny)+Ny.*(( ...
  -2).*(dNxdy.*dNydx+dNydy.*(dNxdx+2.*dNydy))+(-2).*(d2Nxdxdy+2.* ...
  d2Nydydy).*Ny+((-1).*dNxdy.^2+2.*dNxdy.*dNydx+2.*dNydy.*(dNxdx+2.* ...
  dNydy)).*Ny.^2+2.*d2Nydydy.*Ny.^3)+Nx.^2.*((-2).*d2Nxdxdy+(-1).* ...
  d2Nydxdx+(-1).*d2Nydydy+Ny.*((-1).*(dNxdy+(-2).*dNydx).*(2.*dNxdy+ ...
  dNydx)+(dNxdx+dNydy).*(2.*dNxdx+dNydy)+(2.*(d2Nxdxdy+d2Nydxdx)+ ...
  d2Nydydy).*Ny))+Nx.*((-2).*dNydx.*(dNxdx+dNydy)+(-1).*(d2Nxdxdx+ ...
  d2Nxdydy+4.*d2Nydxdy).*Ny+2.*dNydx.*(2.*dNxdx+3.*dNydy).*Ny.^2+( ...
  d2Nxdydy+4.*d2Nydxdy).*Ny.^3+dNxdy.*(dNxdx.*((-2)+Ny.^2)+2.* ...
  dNydy.*((-1)+Ny.^2))));
%}



% Q-tensor calculation:

%{
ELx = ((-1).*d2Nxdxdx+(-1).*d2Nydxdy+(-1).*d2Nzdxdz).*K11+K33.*(((-1).* ...
  d2Nxdydy+(-1).*d2Nxdzdz+d2Nydxdy+d2Nzdxdz).*Nx.^2+(-1).*Ny.*(2.* ...
  dNxdy.*dNydy+(-2).*dNydx.*dNydy+dNydz.*dNzdx+dNxdz.*dNzdy+(-2).* ...
  dNzdx.*dNzdy+(dNxdy+(-1).*dNydx).*dNzdz+d2Nxdydy.*Ny+(-1).* ...
  d2Nydxdy.*Ny)+((-1).*(dNxdy+(-2).*dNydx).*dNydz+dNydy.*dNzdx+(-1) ...
  .*dNydx.*dNzdy+2.*dNzdx.*dNzdz+(-1).*dNxdz.*(dNydy+2.*dNzdz)+(-2) ...
  .*d2Nxdydz.*Ny+d2Nydxdz.*Ny+d2Nzdxdy.*Ny).*Nz+((-1).*d2Nxdzdz+ ...
  d2Nzdxdz).*Nz.^2+(-1).*Nx.*(dNxdy.^2+dNxdz.^2+(-1).*dNydx.^2+ ...
  dNydz.^2+(-1).*dNzdx.^2+(-2).*dNydz.*dNzdy+dNzdy.^2+d2Nydzdz.*Ny+( ...
  -1).*d2Nzdydz.*Ny+(-1).*d2Nydydz.*Nz+d2Nzdydy.*Nz))+K22.*(((-1).* ...
  d2Nxdzdz+d2Nzdxdz).*Ny.^2+Nz.*(dNxdz.*dNydy+(dNxdy+(-2).*dNydx).* ...
  dNydz+(-1).*dNydy.*dNzdx+(-2).*dNxdy.*dNzdy+3.*dNydx.*dNzdy+(-1).* ...
  d2Nxdydy.*Nz+d2Nydxdy.*Nz)+(-1).*Ny.*((-3).*dNydz.*dNzdx+dNxdz.*( ...
  2.*dNydz+(-1).*dNzdy)+2.*dNzdx.*dNzdy+(-1).*dNxdy.*dNzdz+dNydx.* ...
  dNzdz+((-1).*d2Nydzdz+d2Nzdydz).*Nx+(-2).*d2Nxdydz.*Nz+d2Nydxdz.* ...
  Nz+d2Nzdxdy.*Nz)+Nx.*(2.*dNydz.^2+(-4).*dNydz.*dNzdy+2.*dNzdy.^2+( ...
  (-1).*d2Nydydz+d2Nzdydy).*Nz));


 ELy = ((-1).*d2Nxdxdy+(-1).*d2Nydydy+(-1).*d2Nzdydz).*K11+K33.*(Nx.*(2.* ...
  dNxdx.*dNxdy+(-2).*dNxdx.*dNydx+(-1).*dNydz.*dNzdx+(-1).*dNxdz.* ...
  dNzdy+2.*dNzdx.*dNzdy+(dNxdy+(-1).*dNydx).*dNzdz+d2Nxdxdy.*Nx+(-1) ...
  .*d2Nydxdx.*Nx)+(d2Nxdxdy+(-1).*d2Nydxdx+(-1).*d2Nydzdz+d2Nzdydz) ...
  .*Ny.^2+(dNxdz.*(2.*dNxdy+(-1).*dNydx)+(-1).*dNxdy.*dNzdx+dNxdx.* ...
  dNzdy+2.*dNzdy.*dNzdz+(-1).*dNydz.*(dNxdx+2.*dNzdz)+d2Nxdydz.*Nx+( ...
  -2).*d2Nydxdz.*Nx+d2Nzdxdy.*Nx).*Nz+((-1).*d2Nydzdz+d2Nzdydz).* ...
  Nz.^2+(-1).*Ny.*((-1).*dNxdy.^2+dNxdz.^2+dNydx.^2+dNydz.^2+(-2).* ...
  dNxdz.*dNzdx+dNzdx.^2+(-1).*dNzdy.^2+d2Nxdzdz.*Nx+(-1).*d2Nzdxdz.* ...
  Nx+(-1).*d2Nxdxdz.*Nz+d2Nzdxdx.*Nz))+K22.*(((-1).*d2Nydzdz+ ...
  d2Nzdydz).*Nx.^2+Nz.*(dNxdz.*((-2).*dNxdy+dNydx)+dNxdx.*dNydz+3.* ...
  dNxdy.*dNzdx+(-2).*dNydx.*dNzdx+(-1).*dNxdx.*dNzdy+d2Nxdxdy.*Nz+( ...
  -1).*d2Nydxdx.*Nz)+Ny.*(2.*dNxdz.^2+(-4).*dNxdz.*dNzdx+2.* ...
  dNzdx.^2+(d2Nxdzdz+(-1).*d2Nzdxdz).*Nx+(-1).*d2Nxdxdz.*Nz+ ...
  d2Nzdxdx.*Nz)+(-1).*Nx.*((-1).*dNydz.*dNzdx+dNxdz.*(2.*dNydz+(-3) ...
  .*dNzdy)+2.*dNzdx.*dNzdy+(dNxdy+(-1).*dNydx).*dNzdz+d2Nxdydz.*Nz+( ...
  -2).*d2Nydxdz.*Nz+d2Nzdxdy.*Nz));
%}
return
end








